### ISSUE TITLE
Update Sass to 3.4.x

### ISSUE THREAD

**Issue by parkr** [github/pages-gem#110]
Ref https://github.com/jekyll/jekyll-sass-converter/issues/31 which stems from a GitHub Support message.

Would you please `bundle update sass` on Pages? alternatively, we can add 'sass' to `lib/github-pages.rb`. Whichever you'd like. :)

/cc @gjtorikian @benbalter

**Comment by ajkochanowicz** [comment]
Thanks, @parkr

**Comment by gjtorikian** [comment]
`bundle update sass` does nothing; `sass` on GitHub Pages is currently set to 3.4.9, which is the latest release. 

![sass](https://cloud.githubusercontent.com/assets/64050/5669567/540e5548-972d-11e4-9871-e1d9c868d1a4.png)

Did you mean, update `jekyll-sass-converter`? We're at 1.2, but 1.3 is out.

**Comment by parkr** [comment]
Then you should be fine, @ajkochanowicz!

@gjtorikian Thoughts on having a separate segment of gems we report but don't lock externally?

**Comment by gjtorikian** [comment]
@parkr You mean basically publishing the Gemfile.lock used by Pages? I think it's A Good Idea. Maybe extend *versions.json* to include that data? @benbalter Does that make sense?

Closing this out, since we are on the furthest Sass we can go. Please reopen if I'm missing something!
