### ISSUE TITLE
Github pages requires an older version of jekyll while my site requires a newer version

### ISSUE THREAD

**Issue by tunnelsup** [github/pages-gem#121]
I have the following output for my github-pages:
```
$ github-pages versions
+-----------------------+---------+
| Gem                   | Version |
+-----------------------+---------+
| jekyll                | 2.4.0   |
```
Yet my site needs required_from_bundler which wasn't introduced until Jekyll 2.5.0. How do I tell github-pages to use Jekyll 2.5.0 so it's compatible with the rest of my site?

I've placed Jekyll version >= 2.5.0 in my gemfile but get this when I try to update:

```
$ bundle update jekyll
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (>= 2.5.0) ruby

    github-pages (= 33) ruby depends on
      jekyll (2.4.0)
```

**Comment by parkr** [comment]
> How do I tell github-pages to use Jekyll 2.5.0 so it's compatible with the rest of my site?

This is not possible. This gem (`github-pages`) is what is used to more exactly replicate GitHub Pages' build process. If you use 2.5.0, you won't be compatible with GitHub Pages. Thus, this gem locks you to 2.4.0, the currently-running version on Pages.

**Comment by gjtorikian** [comment]
@parkr is correct.

If you're ever curious about which versions are running on Pages, check out https://pages.github.com/versions.json.

For this particular problem, you can prebuild the HTML files in `master`, and the pass the output into `gh-pages`. That will get your content live the way you want it.

**Comment by parkr** [comment]
> If you're ever curious about which versions are running on Pages, check out https://pages.github.com/versions.json.

Or https://pages.github.com/versions/
