### ISSUE TITLE
Markdown tables ignored

### ISSUE THREAD

**Issue by doridori** [github/pages-gem#123]
I installed this gem today as I had a few issues with my Jekyll-Now forked blog and I wanted some error output when building the site on github. I have fixed all problems but this one.

The tables in my existing md docs seem to be ignored and output as plain text in <p> tags. I was previously using Marked to generate the html for the pages which worked fine. I thought kramdown may have its own syntax but it seems the format I have used is compatible. I pulled one the example kramdown tables from the docs and that dosent work either. Is there any configuration in this gem that is disabling tables, or is this an issue with kramdown 1.5.0?

This is my table
```
| PS doc dpi* | PS doc res | designing FOR Android density | PS Pt size | Formula            | Android Dp/Sp  |
|-------------|------------|-------------------------------|------------|--------------------|----------------|
| 72dpi       | 320x480    | MD (160 dpi) 1x               | 10         | (72/72) * 1 * 10   | 10             |
| 72dpi       | 480x720    | HD (240 dpi) 1.5x             | 15         | (72/72) / 1.5 * 15 | 10             |
| 72dpi       | 480x960    | XHD (320 dpi) 2x              | 20         | (72/72) / 2 * 20   | 10             |
| 160dpi      | 320x480    | MD (160dpi) 1x                | 10         | (160/72) / 1 * 10  | 22.2           |
| 320dpi      | 640x960    | XHD (320dpi) 2x               | 10         | (320/72) / 2 * 10  | 22.2           |
```

and this is the example i pulled from the doc that also does not work

```
|-----------------+------------+-----------------+----------------|
| Default aligned |Left aligned| Center aligned  | Right aligned  |
|-----------------|:-----------|:---------------:|---------------:|
| First body part |Second cell | Third cell      | fourth cell    |
| Second line     |foo         | **strong**      | baz            |
| Third line      |quux        | baz             | bar            |
|-----------------+------------+-----------------+----------------|
| Second body     |            |                 |                |
| 2 line          |            |                 |                |
|=================+============+=================+================|
| Footer row      |            |                 |                |
|-----------------+------------+-----------------+----------------|
```

Many thanks

**Comment by parkr** [comment]
Which markdown generator are you using? Kramdown has support for tables, but the other 4 supported Markdown generators may not.

**Comment by doridori** [comment]
ah, I am just using the default which i thought was kramdown. Will have a poke around. I just installed the pages gem and added my posts, watching with `jekyll serve --watch`. I thought this gem setup jekyll with exactly the same setup as github pages so didnt think i could specify the generator in use, unless thats part of the `_config` file. Will have a look. Sorry, new to all this :)

**Comment by kleinfreund** [comment]
You can specify whatever markdown processor you want. And kramdown should be the default.

**Comment by doridori** [comment]
ah thanks - im using [jekyll now](https://github.com/barryclark/jekyll-now) which uses `redcarpet` by default - which needs (some extra setup)[http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages] for tables to work - will switch to kramdown

**Comment by doridori** [comment]
@kleinfreund you say anyone you want - am I right in thinking I can old use either

- maruku
- kramdown
- rdiscount
- redcarpet

as these are the [dependencies](https://rubygems.org/gems/github-pages) of the gem?

**Comment by kleinfreund** [comment]
Yeah, you're not limited to kramdown albeit being the current default. The present dependencies will work on GitHub Pages as well.

**Comment by doridori** [comment]
Great thx, kramdown is working for me

**Comment by NicoHood** [comment]
I try to enable tables for my github page. I tried the following:
```
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
```

However I got an email from github:
> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
>
> You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.
>
> For information on troubleshooting Jekyll see:
>
 > https://help.github.com/articles/troubleshooting-jekyll-builds
>
> If you have any questions you can contact us by replying to this email.

So I read this post which stated kramdown enables tables by default. But it does not seem to work in my case. My table looks like this:
```
| Rating    | Security            | Explanation                             |
|-----------|---------------------|-----------------------------------------|
| Excellent | Very secure         | Criteria is met optimal                 |
| High      | Secure              | Criteria is met                         |
| Mid       | Insufficient secure | Criteria is met partly                  |
| Low       | Insecure            | Criteria is no met                      |
| N/A       | Not rated           | Criteria is not available or irrelevant |
```

**Comment by loupipalien** [comment]
remove the 'markdown' setting in site's '_config.yml' file, then add an extra blank line between the headline/text and the table which is working for me.@NicoHood 👍

**Comment by FMCumhaill** [comment]
Still getting this issue? 
If I understand correctly, (Which I clearly don't since it's not working)
* You _don't_ need to change the config.yml at all. 
* You should just add one line between between the headline/text and the table. 

Can someone explain what "add one line between the headline/text and the table. " means?
