### ISSUE TITLE
ruby version >= 2.0 is required for github-pages

### ISSUE THREAD

**Issue by paulhankin** [github/pages-gem#136]
https://help.github.com/articles/using-jekyll-with-pages/ claims that ruby 1.9.3 is sufficient to install github-pages, but it's not.

$ sudo gem install github-pages
ERROR:  Error installing github-pages:
	public_suffix requires Ruby version >= 2.0.

The same problem occurs if you use bundler.

**Comment by envygeeks** [comment]
It seems this page has been updated @paulhankin because that help page currently lists 2.0.0 as well the new Jekyll3 (soon to be released) has dropped support for 1.9.3 too.

**Comment by parkr** [comment]
@paulhankin Sorry to say that you will need Ruby 2.0 or greater very soon! GitHub Pages is upgrading to Jekyll 3 which requires it, as @envygeeks said. #175.
