### ISSUE TITLE
liquid-2.6.1 gives warning: duplicated key at line 46 ignored: "ind

### ISSUE THREAD

**Issue by azizur** [github/pages-gem#137]
Hi,

I am just trying to use the `github-pages` gem. After installing the gem `liquid-2.6.1` was also installed as dependency.

When I run `jekyll serve` or `bundle exec jekyll serve` I am getting the following warning:
```
/Users/{removed}/.rvm/gems/ruby-2.2.1/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
```

Having look up for outdated gems I am seeing quite a few gems have been updated:
```
$ bundle outdated
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...

Outdated gems included in the bundle:
  * jekyll (2.5.3 > 2.4.0)
  * jekyll-redirect-from (0.7.0 > 0.6.2)
  * blankslate (3.1.3 > 2.1.2.4)
  * html-pipeline (1.11.0 > 1.9.0)
  * jekyll-sass-converter (1.3.0 > 1.2.0)
  * kramdown (1.7.0 > 1.5.0)
  * liquid (3.0.2 > 2.6.1)
  * maruku (0.7.2 > 0.7.0)
  * parslet (1.7.0 > 1.5.0)
  * pygments.rb (0.6.3 > 0.6.1)
  * rdiscount (2.1.8 > 2.1.7)
  * redcarpet (3.2.3 > 3.1.2)
```

Looking at https://pages.github.com/versions/ liquid-2.6.1 is the correct dependency. I am wondering why I am getting this warning?

**Comment by parkr** [comment]
This has been fixed on `master`, but @benbalter didn't release a new gem for it yet. https://github.com/github/pages-gem/pull/132

**Comment by jolux** [comment]
In the mean time, what shall we do to avoid this? I currently can't use jekyll because of it.

**Comment by parkr** [comment]
@jolux You can't use Jekyll because of this? It's just a warning, not an erro.

**Comment by jolux** [comment]
On 9 May 2015, at 23:16, Parker Moore wrote:

> @jolux You can't use Jekyll because of this? It's just a warning, not 
> an erro.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/github/pages-gem/issues/137#issuecomment-100577492
It failed bundle exec jekyll build and bundle exec jekyll serve etc for 
me. I fixed it by changing the Gemfile.lock to use 2.6.2. It's a hack 
that will break the next time I bundle update before it's fixed upstream 
but it works for now.

Sincerely,

Ben Klebe

**Comment by parkr** [comment]
@benbalter would you mind bumping this gem version?

**Comment by jolux** [comment]
Seems weird that the published gem is behind. Should/can I make one with the version here? This is kind of urgent.

**Comment by parkr** [comment]
@jolux v35 has been released (thanks @benbalter!). Please try it.

**Comment by jolux** [comment]
On 10 May 2015, at 14:37, Parker Moore wrote:

> @jolux v35 has been released (thanks @benbalter!). Please try it.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/github/pages-gem/issues/137#issuecomment-100679530
Well it's definitely fixed my issues. Thank you!

Sincerely,

Ben Klebe

**Comment by parkr** [comment]
@azizur Please close.
