### ISSUE TITLE
Relax pygments.rb dependency

### ISSUE THREAD

**Issue by TWiStErRob** [github/pages-gem#144]
Please modify the pygments.rb dependency version from [`0.6.1`](https://github.com/github/pages-gem/blob/v37/lib/github-pages.rb#L25) to `~>0.6.1` or better yet `>=0.6.3` for the following reasons:
 * [jekyll 2.4.0 uses `~0.6.0`](https://github.com/jekyll/jekyll/blob/v2.4.0/jekyll.gemspec#L39)
 * [`<0.6.3` is not compatible with Windows 7](https://github.com/jekyll/jekyll/issues/2789)
 * [there's no way to override the version in the `Gemfile`](https://github.com/bundler/bundler-features/issues/20)

I'm trying to use this one:
```ruby
source 'https://rubygems.org'
# for some reason omitting the verison defaults to 0
gem 'github-pages', '>=37'
# contains fix for https://github.com/tmm1/pygments.rb/pull/90
gem 'pygments.rb', '>=0.6.3'
# temporarily while wdm 0.1 merges https://github.com/Maher4Ever/wdm/pull/16
gem 'wdm', :git => 'git://github.com/lowjoel/wdm.git' if Gem.win_platform?
```

and result is:
```
Bundler could not find compatible versions for gem "pygments.rb":
  In Gemfile:
    github-pages (>= 37) x64-mingw32 depends on
      pygments.rb (= 0.6.1) x64-mingw32

    pygments.rb (~> 0.6.0) x64-mingw32

    pygments.rb (>= 0.6.3) x64-mingw32
```

**Comment by benbalter** [comment]
@TWiStErRob can you submit a pull request to bump Pygments from 0.6.1 to 0.6.3?

**Comment by TWiStErRob** [comment]
@parkr thanks for jumping in with the PR and following through. No more hacking to make it build, yay! :)
