### ISSUE TITLE
Support for GitHub metadata when developing locally?

### ISSUE THREAD

**Issue by WasabiFan** [github/pages-gem#161]
As far as I can tell, there is no way to test parts of a Jekyll site that [uses `site.github.*`](https://help.github.com/articles/repository-metadata-on-github-pages/) variables locally without pushing them to GitHub. Am I missing something there?

If not, I think that that feature would be a great addition to this gem. It would simply perform the same function that the build server's configuration performs in adding those metadata variables, but do it locally.

Is this a feature that you would be willing to include if I wrote the code for it?

**Comment by parkr** [comment]
We have this already, though it's not a part of this gem: https://github.com/jekyll/github-metadata

I'd be interested in seeing it distributed with this gem.

**Comment by WasabiFan** [comment]
Ahhhh great, thanks! I think this should be packaged with this gem and documented somewhere -- maybe even on that docs page that I mentioned.

**Comment by Starefossen** [comment]
:+1:
