### ISSUE TITLE
Github Hosted versions.json file is out of date

### ISSUE THREAD

**Issue by Stargator** [github/pages-gem#166]
Within the [Jekyll doc page for Github-Pages](http://jekyllrb.com/docs/github-pages/), it states:

> To use the currently-deployed version of the gem in your project, add the following to your Gemfile:
```ruby
> source 'https://rubygems.org'
> 
> require 'json'
> require 'open-uri'
> versions = JSON.parse(open('https://pages.github.com/versions.json').read)

> gem 'github-pages', versions['github-pages']
```
> This will ensure that when you run bundle install, you have the correct version of the github-pages gem.

The versions.json file it points to on github lists github-pages version 37 instead of the current 38.

Is there a way to automate that? Maybe have versions.json pulled from this repo. Which would mean adding in a file not used by the gem.

**Comment by gjtorikian** [comment]
Site rebuilt. We haven't automated this....yet.

**Comment by Stargator** [comment]
Thanks @parkr & @gjtorikian
