### ISSUE TITLE
JS: Support ES6 

### ISSUE THREAD

**Issue by parkr** [github/pages-gem#170]
Heyo,

I know generally plugin requests are not allowed here. Just want to get a reading on what supporting other JavaScripts would be like. We already opened the door by allowing jekyll-coffeescript. What about ES6? (https://github.com/jekyll/jekyll/issues/3863)

@thejameskyle wrote [a plugin for this](https://github.com/thejameskyle/jekyll-babel). How do you measure success and willingness to support these other plugins?

**Comment by thejameskyle** [comment]
:cry:

**Comment by parkr** [comment]
@thejameskyle Would you mind writing support@github.com about this? I don't think we can do anything here from the open source end of things.

**Comment by lukefrake** [comment]
@thejameskyle did you speak to support, would be awesome to get this in :+1:

**Comment by thejameskyle** [comment]
I've written to support a number of times about this and have never received a response.

**Comment by sunjay** [comment]
Anything?

**Comment by sunjay** [comment]
For people who land on this issue, I made a starter project that will help you get es6 transpilation working and then publish it to Github pages easily. 

It isn't nearly as good as them actually adding support but it may work for you in the meantime:

https://github.com/sunjay/gh-pages-es6-starter
