### ISSUE TITLE
List jekyll plugins supported by gh-pages

### ISSUE THREAD

**Issue by ngoldman** [github/pages-gem#171]
I saw https://github.com/blog/2053-easier-feeds-for-github-pages today and am wondering if there's a list of jekyll plugins supported by github pages. I can see a few here and there in the [releases](https://github.com/github/pages-gem/releases) but it would be great to have a list in the readme so folks can easily see what works on gh-pages.

**Comment by parkr** [comment]
@ngoldman Here they are! https://pages.github.com/versions/

**Comment by parkr** [comment]
If you would like a more programmatic means of determining compatibility, there's JSON for that, too:

https://pages.github.com/versions.json

**Comment by ngoldman** [comment]
Thank you! Would still be nice to see what jekyll plugins are supported without inspecting individual gem dependencies. I think it would particularly benefit folks who are not rubyists or advanced programmers but just want to get a gh-pages jekyll site up and running and are unaware of the extra goodies like emojis, redirects, atom feeds, sitemaps, etc. Thinking of users of projects like http://jlord.us/forkngo/.
