### ISSUE TITLE
transitive dependency (activesupport) breaks install (as it requires ruby>=2.2.2)

### ISSUE THREAD

**Issue by csabapalfi** [github/pages-gem#181]
A transitive dependency requires ruby 2.2.2 and breaks the installation:
https://rubygems.org/gems/activesupport/versions/5.0.0.beta1

**Comment by benbalter** [comment]
@csabapalfi Do you know what dependency requires it? Do you have a suggestion on how to fix it?

**Comment by benbalter** [comment]
See also https://travis-ci.org/github/pages-gem/builds/100162574 which shows tests passing for 2.0, 2.1, 2.2, and 2.3.

**Comment by alexconst** [comment]
I tried to install the github-pages gem in a clean installation of Ubuntu Wily and I get the same problem. Error message:
```
Fetching: activesupport-5.0.0.beta1.gem (100%)
ERROR:  Error installing github-pages:
       activesupport requires Ruby version >= 2.2.2.
```
system version:
```
root@9fe80b7fc28a:/# cat /etc/issue
Ubuntu 15.10 
root@9fe80b7fc28a:/# ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```

ad hoc test:
```
docker run -t -i ubuntu:wily /bin/bash
apt-get update
apt-get install -y ruby-dev bundler
gem install github-pages
```

**Comment by alexconst** [comment]
Workaround
~~~
gem install activesupport          # yeah, it works if you install it beforehand
apt-get install -y zlib1g-dev
gem install github-pages
~~~

**Comment by benbalter** [comment]
@parkr any idea what's going on here?

**Comment by csabapalfi** [comment]
jemoji and jekyll-mention depends on older versions of html-pipeline

before [this commit](https://github.com/jch/html-pipeline/commit/8488f677751e670608109667f54f74abbdcf8965) htmlpipeline didn't constrain activesupport version so 5.0.0beta1 would get installed which requires ruby>=2.2.2

**Comment by mmoll** [comment]
I guess this issue can get closed then?

**Comment by parkr** [comment]
@mmoll Correct! I believe all the dependencies are in line now and CI is passing.

**Comment by alexconst** [comment]
Hi guys,
guess who is back?
This little bugger is!
Fortunately the workaround mentioned above still works.

~~~text
root@jekyll:~# ruby -v
ruby 2.2.3p173 (2015-08-18) [x86_64-linux-gnu]

root@jekyll:~# /usr/bin/gem install --version 55 --no-user-install --no-document github-pages
ERROR:  Error installing github-pages:
        activesupport requires Ruby version >= 2.2.2.

root@jekyll:~# /usr/bin/gem install activesupport
Fetching: activesupport-4.2.6.gem (100%)
Successfully installed activesupport-4.2.6
Parsing documentation for activesupport-4.2.6
Installing ri documentation for activesupport-4.2.6
Done installing documentation for activesupport after 9 seconds
1 gem installed

root@jekyll:~# /usr/bin/gem install --version 55 --no-user-install --no-document github-pages
Fetching: html-pipeline-2.3.0.gem (100%)
-------------------------------------------------
...
Fetching: github-pages-55.gem (100%)
---------------------------------------------------
Thank you for installing github-pages!
GitHub Pages recently upgraded to Jekyll 3.0, which
includes some breaking changes. More information:
https://github.com/blog/2100-github-pages-jekyll-3
---------------------------------------------------
Successfully installed github-pages-55
24 gems installed
~~~

Someone has been skipping their CD veggies :p

**Comment by alexconst** [comment]
Race condition with @parkr just releasing v56.
Just tested it and it still happens with v56.

**Comment by denisrosset** [comment]
Ubuntu 15.10, stock Ruby installation, got the same problem, and the workaround works perfectly.

Thanks @alexconst!

**Comment by gabmontes** [comment]
Same issue in Debian 8.3. @alexconst workaround worked for me too!

```
gem install activesupport
gem install github-pages
```

**Comment by scopelandit** [comment]
gem install activesupport -v 4.2.6

**Comment by mitjajez** [comment]
(`sudo`) `gem install activesupport -v 4.2.7`
and put
`gem 'activesupport', '4.2.7'` in Gemfile before `gem 'github-pages'`
and do `bundle update` before (or if fails) `bundle install`

**Comment by dret** [comment]
this one still seems to be alive and kicking. struggling to set up jekyll on a second MacOS machine. `jekyll serve` works fine on the first machine. on the second machine i need to do `bundle exec` to make anything work (i have several repos where i am using github pages and jekyll), but in one repo even then it doesn't work:

```
Fetching dependency metadata from https://rubygems.org/.
activesupport-5.0.0 requires ruby version >= 2.2.2, which is incompatible with
the current version, ruby 2.0.0p648
```

https://github.com/dret/HTML5-overview is where the Gemfile lives.

**Comment by DirtyF** [comment]
Has it not been taken care of in https://github.com/jekyll/jekyll/pull/5100 ?
