### ISSUE TITLE
Github Hosted versions.json file is out of date

### ISSUE THREAD

**Issue by boturnbow** [github/pages-gem#192]
Thanks for the rev to jekyll v3. Could you please update https://pages.github.com/versions.json

This is similar to https://github.com/github/pages-gem/issues/166

**Comment by benbalter** [comment]
@boturnbow thanks for the issue. https://pages.github.com/versions.json should now be updated (it may require a hard refresh of your browser).

**Comment by boturnbow** [comment]
:thumbsup:
