### ISSUE TITLE
Allow highlighter: false in config

### ISSUE THREAD

**Issue by hafen** [github/pages-gem#198]
Being forced to use rouge is a bit strict.  At the least it would be nice to set `highlighter: false`.  I have syntax that renders terribly with rouge and I'd rather leave it untouched and hit it with a custom js highlighter after.

**Comment by ktzanev** [comment]
:+1:

 When I install github-pages in local `highlighter: none` or `highlighter: null` works. But when pushed to GitHub, rouge is not disabled. I also tried the `kramdown` option `syntax_highlighter: none`, without success. 

Finaly I was able to turn off `rouge` by combining [kramdown's `syntax-highlighter-opts` option](http://kramdown.gettalong.org/options.html#option-syntax-highlighter-opts) with the [rouge's `diable` option](http://kramdown.gettalong.org/syntax_highlighter/rouge.html) : 

    syntax_highlighter_opts:
      disable : true

Probably the documentation should be updated if this is the way to disable rouge.

**Comment by benbalter** [comment]
Thanks @ktzanev. That fix is likely going to be the simplest for now.

To note, the options are part of your `kramdown` config, thus in `_config,yml`:

```yml
kramdown: 
  syntax_highlighter_opts:
    disable : true
```

This will disable syntax highlighting on GitHub Pages. I'll work on getting this reflected in the docs.

**Comment by hafen** [comment]
Thanks!  That works for me.
