### ISSUE TITLE
Github Hosted versions.json file is out of date

### ISSUE THREAD

**Issue by DirtyF** [github/pages-gem#199]
similar to #166

**Comment by parkr** [comment]
Both https://pages.github.com/versions/ and https://pages.github.com/versions.json now have the latest data.

**Comment by DirtyF** [comment]
Thanks @parkr FYI I subscribed to https://libraries.io/rubygems/github-pages/45 and it seems that versions pages on Github are updated slightly later, buy you already know that I imagine.
