### ISSUE TITLE
Permalinks/relative URLs issue

### ISSUE THREAD

**Issue by hatondog** [github/pages-gem#201]
I'm having an issue with permalinks on my deployed Github pages site, that I can't reproduce locally. I assumed this was due to the recent upgrade, but have since updated my local gem, and still can't reproduce.

My URLs for collections used to show as:
http://hatondog.com/podcasts/hmm-interesting-choice/1/amy-macdonald-this-is-the-life/
But are now showing as:
http://hatondog.com/podcasts/hmm-interesting-choice/1/1/

In my project's config I have:
collections:
  episodes:
    output: true
    permalink: /podcasts/:path/:title/

The files in these collection are 1.md, 2.md, etc... and in the front-matter I have the episode title, i.e. "Amy Macdonald - This Is The Life".

For some reason this has stopped being picked up in the URL (for the ":title" in the config), and as I say I still can't reproduce this locally - as in, I still see the URLs in the form "/1/amy-macdonald-this-is-the-life/"

Any help greatly appreciated, apologies if this is in the wrong place.

Regards.

**Comment by benbalter** [comment]
Clicking the first link above, it appears this issue has been resolved.
