### ISSUE TITLE
Drafts are no longer ordered by modification time

### ISSUE THREAD

**Issue by sordina** [github/pages-gem#203]
It seems that when I updated to the latest version of github-pages for local development, the ordering of my draft-posts has changed from modification time, to the current day.

I'm not sure what version this began on, but I was previously using "github-pages (39)", I'm now using "github-pages (45)".

Example:

	Post index
		Feb 9, 2016	Tech I Won't Work With: AngularJS
		Feb 9, 2016	Why Quora Sux
		Feb 9, 2016	Value and Respect - Domestic Vs. Global
		Feb 9, 2016	Is there a trend towards more downvoting on /r/haskell?
		Feb 9, 2016	Social Media as an Index
		...
	Directory Listing
		> ls -lt _drafts
		-rw-r--r--  1 lyndon  staff  10337  9 Feb 09:35 promises-architecture.markdown
		-rw-r--r--  1 lyndon  staff   3158  8 Feb 12:14 why_quora_sux.markdown
		-rw-r--r--  1 lyndon  staff    222  8 Feb 11:44 play_bach.markdown
		-rw-r--r--  1 lyndon  staff     89  8 Feb 11:29 play-bach-suite-6-prelude.markdown
		-rw-r--r--  1 lyndon  staff   2919  8 Feb 09:55 naming-things.markdown
		...

This is probably an upstream issue, but I've had a look in the Jekyll source and can't seem to track it down. Hopefully someone has an idea about why this is occurring, otherwise just close the issue as [upstream] and I'll re-raise the issue with the Jekyll project.

**Comment by benbalter** [comment]
> This is probably an upstream issue, but I've had a look in the Jekyll source and can't seem to track it down. Hopefully someone has an idea about why this is occurring, otherwise just close the issue as [upstream] and I'll re-raise the issue with the Jekyll project.

@sordina it does indeed sounds like a Jekyll issue, as GitHub Pages doesn't touch drafts. Please open an issue over in https://github.com/jekyll/jekyll. Thanks.

**Comment by sordina** [comment]
The fix has been made upstream now: https://github.com/jekyll/jekyll/pull/4611

**Comment by sordina** [comment]
@benbalter : This issues has been resolved upstream in release 3.1.2 [1] - Will the update of pages to this release be done automatically, or will there have to be an issue raised?

[1] - https://github.com/jekyll/jekyll/compare/v3.1.2...master

**Comment by benbalter** [comment]
@sordina we're still in the process of vetting Jekyll 3.1.x. We like to give releases a bit of time to bake in the wild, to uncover new bugs that may have been introduced, and to ensure that it's compatible with the plugins used. Once that process is complete, I suspect we'll update to the latest patch version of the 3.1.x branch. :smile:

**Comment by sordina** [comment]
@benbalter Ah that's good to hear. Thanks for giving me a bit of insight into the pages process :)
