### ISSUE TITLE
Pagination doesn't work in safe mode

### ISSUE THREAD

**Issue by TWiStErRob** [github/pages-gem#208]
Steps to reproduce:
 * `jekyll new .`
 * append to `config.yml`:
	```yml
	gems:
	  - jekyll-paginate

	paginate: 2
	paginate_path: "/page:num/"
	safe: false
	```
 * change `index.html`:
	```diff
	-{% for post in site.posts %}
	+{% for post in paginator.posts %} 

	+<nav id="pagination">
	+    {% if paginator.previous_page %}
	+      {% if paginator.previous_page == 1 %}
	+        <a href="{{ site.baseurl }}/">&laquo;</a>
	+      {% else %}
	+        <a href="{{ site.baseurl }}/page{{ paginator.previous_page }}/">&laquo;</a>
	+      {% endif %}
	+    {% endif %}
	+
	+    {% if paginator.next_page %} 
	+      <a href="{{ site.baseurl }}/page{{ paginator.next_page }}/">&raquo;</a>
	+    {% endif %} 
	+</nav>
	```
 * create some posts (I duplicated `welcome-to-jekyll` a few times)

Test the site and notice that pagination works nice.

Now, https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change states that `safe: true` is mandatory and cannot be changed. But to have pagination I need to turn `safe: false`, otherwise it won't work: with safe mode enabled the generated index.html is empty, it doesn't show the posts.

How can I test the page locally with the allowed optional gems in safe mode to be closest to GitHub pages builds?

**Comment by benbalter** [comment]
@parkr is possible with `safe: true` and no whitelist, all plugins are blacklisted?

**Comment by TWiStErRob** [comment]
Ah, that actually makes sense :) Adding
```yaml
whitelist:
  - jekyll-paginate
```
allows me to test locally with safe mode on.

Would it be possible to incorporate this into the gem to automatically build in a github-like environment? Even at the cost of calling `github-gem serve` instead of `jekyll serve`.

**Comment by benbalter** [comment]
> Would it be possible to incorporate this into the gem to automatically build in a github-like environment? Even at the cost of calling github-gem serve instead of jekyll serve.

Yep. We're working on just that over in #209.

**Comment by TWiStErRob** [comment]
Awesome, keep up the good work!

**Comment by parkr** [comment]
#209 has shipped! Use v62 or later.
