### ISSUE TITLE
Problem with backticks syntax highlight

### ISSUE THREAD

**Issue by ggarnier** [github/pages-gem#211]
I'm using `github-pages` gem version 48. When I use the backticks syntax highlight for source code formatting and run `jekyll serve` locally, the syntax isn't recognized - the triple backticks and source code are directly printed in the HTML. But if I push this to github pages, the syntax highlight  works fine.

If I change this syntax to `{% highlight language %}`, the opposite happens: it works locally, but I get an error from github pages. Am I doing something wrong?

Here is a slice from my `_config.yml` file:

```
markdown: kramdown
highlighter: rouge
```

**Comment by vincent-zurczak** [comment]
Did you try this?

```
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
```

This is supposed to work on Github.
But personnally, I could not make it work locally (problem with backticks).

For me, github-pages 3.0.3 is not working correctly. I wrote a [blog article](https://vzurczak.wordpress.com/2016/02/12/github-pages-kramdown-rouge-jekyll-3-0-the-final-struggle/) about this switch to Jekyll 3.0... I hope github-pages will soon switch to [Jekyll 3.1.2](https://github.com/jekyll/jekyll/issues/4448), which is supposed to fix this problem.

**Comment by benbalter** [comment]
@ggarnier, @vincent-zurczak is correct, the following configuration should work locally:

```yml
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
```

We're working over in https://github.com/github/pages-gem/pull/209 to set this by default.

**Comment by ggarnier** [comment]
@vincent-zurczak @benbalter that's it, thanks!
