### ISSUE TITLE
YAML variables not working in layouts

### ISSUE THREAD

**Issue by jeremenichelli** [github/pages-gem#215]
In my personal site each page has a type which I use to generate unique classes on the markup. Recently I noticed that on my site hosted on GitHub that variable wasn't working. It works locally, it always worked previously, it just doesn't work on my site https://jeremenichelli.github.io

In each post the header should have a `post--header` class, but it has nothing. It works for the rest of the pages which is even weird.

Did anyone had a similar problem after last update to Jekyll 3.0.3?

**Comment by benbalter** [comment]
@jeremenichelli it's hard to diagnose site-specific issues via this repository's issues, but we'd be glad to help get your squared away. Would you be able to [contact support](https://github.com/contact?form%5Bsubject%5D=GitHub%20Pages) with additional details?

**Comment by jeremenichelli** [comment]
Will do. thank you and sorry for the noise.

**Comment by benbalter** [comment]
No need to apologize. Sorry you're having trouble, but looking forward to getting you squared away.

**Comment by jeremenichelli** [comment]
Just a heads up! After some debugging (and pay attention to the fact that GitHub Pages just passed from 2.x to 3.x on Jekyll) I discovered that is actually a change in Jekyll's behavior.

What I need to find out with their maintainers now is if it is expected or a bug actually.

**Comment by jeremenichelli** [comment]
Aaaaand here it is https://github.com/jekyll/jekyll/issues/4571
