### ISSUE TITLE
kramdown hard_wrap not working for hyperlinks

### ISSUE THREAD

**Issue by alexconst** [github/pages-gem#231]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (either `gem update pages-gem` or `bundle update pages-gem`)

### This issue affects

- [X] Building sites locally
- [X] The site generated by GitHub Pages

### What did you do (e.g., steps to reproduce)
- update site to use kramdown with `_config.yml` as follows:
~~~
markdown: kramdown
kramdown:
    input: GFM 
    hard_wrap: false
highlighter: rouge
~~~

- create a valid markdown post with:
~~~markdown
**Download Packer:**  
<https://www.packer.io/downloads.html>  
<https://github.com/mitchellh/packer>
~~~
Note that there are 2 spaces at the end of the lines. Which was enough for redcarpet.

### What did you expect to happen?

- For naked links to get the same treatment as text. Namely for an html output with a layout like this:
~~~
Download Packer:
https://www.packer.io/downloads.html
https://github.com/mitchellh/packer
~~~

### What happened instead?

- Text gets htmlized into a single line:
~~~
Download Packer: https://www.packer.io/downloads.html https://github.com/mitchellh/packer
~~~

Any option or extension to fix this?

Thanks.

**Comment by parkr** [comment]
Hey @alexconst! This looks like a solid bug report to me. The markdown parser we use is called [kramdown](https://github.com/gettalong/kramdown/). Would you please file this with them? We use the GFM parser there and I know it doesn't perfectly match what GitHub has here on GitHub.com.

Here:

**Download Packer:**  
<https://www.packer.io/downloads.html>  
<https://github.com/mitchellh/packer>
