### ISSUE TITLE
site.github.url metadata provides http url creating a mixed content error when used on github.io pages

### ISSUE THREAD

**Issue by elationfoundation** [github/pages-gem#238]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [ ] Update to the latest Gem version (either `gem update pages-gem` or `bundle update pages-gem`)
Not a build "error" but a configuration request.

### This issue affects

- [X] The site generated by GitHub Pages
- [ ] Building sites locally

### What did you do (e.g., steps to reproduce)

- Create a github.io page
- install HTTPS everywhere or configure browser to reject mixed content
- Add local static CSS file to github page prepended with site.github.url

```
<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.github.url }}">
```

- open chrome developers tab and go to network section
- load website in browser
- encounter mixed content error that stops css from loading.

### What did you expect to happen?

I expected the site url protocol to match the protocol provided by github pages.

### What happened instead?

The url I was provided was HTTP while the github page was delivered using HTTPS

### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

I plan to create a fix for this in the next few minutes. But it can be recreated using the following commit in my repository. (It is easy enough to reproduce without, but I thought I'd make it available.)

https://github.com/OpenInternet/copilot/tree/219d9508737b1a0b0edd14380fece63cb3d8c60d

**Comment by parkr** [comment]
HTTPS is not officially supported. Once it is, `jekyll-github-metadata` will be updated with this to ensure HTTPS is used everywhere. Thanks for your understanding!

**Comment by gauntface** [comment]
I just got by this as well, one solution is to remove the specific HTTP protocol and use what ever the page is served over:

    {{ "/css/main.css" | prepend: site.github.url | replace: 'http://', '//' }}

**Comment by petrgazarov** [comment]
If you are using Cloudflare, you can take advantage of [Automatic HTTPS Rewrites](https://www.cloudflare.com/website-optimization/automatic-https-rewrite/)

**Comment by mattn** [comment]
GitHub enable HTTPS on GitHub Pages.

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

So `site.url` always be wrong. Most of GitHub users will add workaround `{{ site.url | replace: 'http://', '//'}}`. How about to add new attribute like `site.url_noscheme` or something?

**Comment by parkr** [comment]
When you click the "Enforce HTTPS" button, your `site.github.url` should contain `https://`.

**Comment by dahlbyk** [comment]
@parkr thanks for the quick fix on this.

My 2¢ having just been through this transition: `site.github.url`, or some other variable, should reflect the request protocol, not Enforce HTTPS, as existing sites won't want to enable Enforce HTTPS until they confirm everything works as expected.
