### ISSUE TITLE
Using third-party npm/bower dependencies with `github-pages`

### ISSUE THREAD

**Issue by azizur** [github/pages-gem#240]
### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

---
I have just become aware of `jekyll-sass-converter` project yesterday, as I was working on a project using `github-pages` gem. As `github-pages` uses  `jekyll-sass-converter` repo as a dependency, So I am raising this issue here for discussion and request for feature to solve a challenge of using `github-pages` with modern front-end components/libraries. 

Here is the challenge I have on my hand. I have a project that uses `bootstrap-sass` brought in using npm like many other modern front-end components and libraries. The sass files in my `sass-dir` reference the respective `bootstrap` component selectively. This is because I want to be able to only bundle those components/styles that my project requires and keep my payload a slim as possible.

What I am trying to do is __not check-in__ `node_modules` into the project git repo and still generate all the styles for the site. It is not considered a good practice to version control third party library/component into your project repo.

This is my challenge, how can I generate the CSS (using third-party front-end component/libraries) so that I can get GitHub to process my css/sass files  without checking-in all the `node_modules`?

When I look into it here are my options:
1) Do not use sass, that's not really an option.
2) Commit `node_modules` into my repo, that is considered bad practice in modern development.
3) Generate compiled CSS and commit them into my repo. I can live with this but I am not aware of an option to do this using `jekyll-sass-converter`, yet.
4) Use another tool to generate the CSS. Do we really have to use another asset-pipeline tool?
5) Github add supports for bower and npm dependencies. This is probably a big ask and can happen given enough people wants it and Github agrees with it.

**So how can we address this challenge of using third-party dependencies with `github-pages`?**

**Comment by adamaltmejd** [comment]
I just copy the relevant bootstrap files to my _sass directory using grunt. Works great! https://github.com/adamaltmejd/adamaltmejd.github.io

**Comment by azizur** [comment]
@adamaltmejd that's equivalent of my option 2 above. In fact its even worst because you'll now maintain a third-party package in your project `_sass` directory. This creates extra work to download the source files and manually copy them over to your `_sass` directory.

**Comment by benbalter** [comment]
@azizur thanks for taking the time to open this issue. I do not believe this is an issue specific to GitHub or GitHub Pages, but rather is either a general Jekyll question, or a question specific to the SASS converter. There's work within Jekyll core to add theme support, which should hopefully resolve the issue for you. 

FWIW, for my own site, I user bower to install bootstrap and other dependencies to `/assets/vendor` and use the `.gitignore` file to ignore any paths I do not need. Symlinks, although not ideal, are also an option.
