### ISSUE TITLE
Feedback on versioned local configuration defaults and overrides

### ISSUE THREAD

**Issue by benbalter** [github/pages-gem#256]
If you'd like to be an early tester of the new versioned local configuration defaults and overrides, please change the following line in your Gemfile:

```ruby
gem 'github-pages'
```

To:

```ruby
gem 'github-pages', :group => :jekyll_plugins
```

This will allow the GitHub Pages Gems to set local configuration defaults (e.g., GitHub-flavored Markdown for Kramdown), and overrides (e.g., safe mode), without any additional action or configuration on your part. If you're interested, you can see the actual configuration in [`configuration.rb`](https://github.com/github/pages-gem/blob/master/lib/github-pages/configuration.rb).

*If you don't mind being an early adopter, and are comfortable making the above change, we'd love to hear your feedback. Do things work as expected? Any strange behavior? Anything you'd improve?*

**Comment by mattr-** [comment]
If I update to this version, would I need to change how i'm using the `github-pages` gem if I don't want to be an early adopter?

**Comment by parkr** [comment]
> would I need to change how i'm using the github-pages gem if I don't want to be an early adopter?

@mattr- Nope! When added to the `:jekyll_plugins` group, it runs the `:after_reset` hook present in `lib/github-pages.rb` to set the configuration. If you _don't_ do this, these configuration changes will not affect your system, as the hook will not be registered.

**Comment by budparr** [comment]
Sorry for jumping in. Will using this will make any plugins I use behave as if my local environment were GH Pages, that is, a non-whitelisted plugin would not work? As well, config settings would be overridden/ignored as though on GH Pages?

**Comment by dentarg** [comment]
@budparr yes, with github-pages v68 `bundle exec jekyll build` now fails if your `_config.yml` contains non-whitelisted plugins, unless you use the `DISABLE_WHITELIST` flag, that was not the case with v67 (see example of that at https://github.com/klubbdinmamma/klubbdinmamma.github.io/commit/cba15f26b9e4bcdb868e44b9f4527c9d3a47a8dd#commitcomment-17040758)

**Comment by benbalter** [comment]
Thanks everyone, for the feedback.
