### ISSUE TITLE
Jekyll 3.0.4 breaks local site auto-regeneration

### ISSUE THREAD

**Issue by sethjackson** [github/pages-gem#280]
### This issue affects

- [ ] The site generated by GitHub Pages
- [X] Building sites locally

### What did you do (e.g., steps to reproduce)

In my `Gemfile`:

```
gem "github-pages"
```

    $ bundle update

    $ bundle exec jekyll serve

### What did you expect to happen?

I expected auto-regeneration to work.

### What happened instead?

I received the following error in my console:

```
Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
```

and my site no longer rebuilt automatically locally.

Running with:

    $ bundle exec jekyll serve --watch

had no effect.

### Additional information

I do not have: `auto: true` set in my `_config.yml`.

This works correctly on Jekyll 3.0.3 (`github-pages` version `72`) but not on Jekyll 3.0.4 (`github-pages` version `73` onwards).

Ruby version: `ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]`

**Comment by lizell** [comment]
Can confirm this with versions below:
```
      Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
      GitHub Pages: github-pages v74
      GitHub Pages: jekyll v3.0.4
```
```
[2016-04-23 12:02:02] INFO  WEBrick 1.3.1
[2016-04-23 12:02:02] INFO  ruby 2.1.7 (2015-08-18) [x86_64-darwin14.0]
```

**Comment by sethjackson** [comment]
I just updated to version `75` and `bundle exec jekyll serve` is still not working for me with or without `--watch`. I get the same error as above.

Maybe I'm just doing something wrong?

**Comment by DirtyF** [comment]
```
Installing github-pages 75 (was 69)
Bundle updated!

~/code/frank.taillandier.me gh-pages* 16s
be jekyll s
Configuration file: /Users/frank/code/frank.taillandier.me/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
            Source: /Users/frank/code/frank.taillandier.me
       Destination: /Users/frank/code/frank.taillandier.me/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.796 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Configuration file: /Users/frank/code/frank.taillandier.me/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

**Comment by parkr** [comment]
This doesn't seem to be a problem with github-pages, but a problem with Jekyll 3.0.4's `Configuration.from`. `#backwards_compatibilize` is destructive and can only be called once on a configuration.

**Comment by kdbanman** [comment]
Also getting this on the following:

```
$ bundle show github-pages
    .gem/ruby/gems/github-pages-75
$ jekyll -v
    jekyll 3.0.4
$ bundle -v
    Bundler version 1.11.2
$ ruby --version
    ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
```

This script will exactly replicate the issue.  (My output is [here](https://gist.github.com/kdbanman/31d665aeae9b194963d3a56abc1bc586)).

```
git init testJekyll
cd testJekyll/
git remote add origin git@github.com:test/testJekyll.git
printf "source 'https://rubygems.org'\ngem 'github-pages', group: :jekyll_plugins" > Gemfile
bundle install
bundle exec jekyll new . --force
bundle exec jekyll serve -w
```

@parkr, now that we know what's causing the issue, is there a workaround?

**Comment by parkr** [comment]
@kdbanman Yes, and I released Jekyll 3.0.5 for this. We'll try to upgrade soon!

**Comment by kdbanman** [comment]
Thanks for the quick response!

**Comment by sethjackson** [comment]
This is working again. Thanks!

**Comment by lizell** [comment]
:+1:

torsdag 28 april 2016 skrev Seth Jackson <notifications@github.com>:
