### ISSUE TITLE
pages-gem is not letting me test plugins locally with DISABLE_WHITELIST=true 

### ISSUE THREAD

**Issue by prufrock123** [github/pages-gem#283]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (either `gem update pages-gem` or `bundle update pages-gem`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)
added [BetterTube plugin](https://github.com/tuananh/BetterTube) to _plugins directory. Tried to build it locally with DISABLE_WHITELIST=true jekyll build and I received the error 
```
  Liquid Exception: Liquid syntax error (line 5): Unknown tag 'youtube' 
```

### What did you expect to happen?
The plugin to run correctly locally.
### What happened instead?
It seems the plugin is still being disabled by the pages-gem
### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):
https://github.com/prufrock123/unearthIsrael

**Comment by parkr** [comment]
`DISABLE_WHITELIST=true` only disables the whitelist limitation – it doesn't allow all plugins. We can document this better but this is expected behaviour.

**Comment by prufrock123** [comment]
Ah ok, thank-you!  So is there a good workflow for building plugins locally and then pushing the built static pages to gh-pages?  It would be nice just so I can still keep my workflow all on my one repo.

My goal is to use the master branch to write code, then my gh-pages branch targets only my _sites directory.  Then I can just push my master branch to the repo, and my gh-pages to the site.  It would be sooooooo cool if I could get it to work!!

**Comment by prufrock123** [comment]
I have tried adding plug-ins by listing them in the _config.yml file as well, but I still get the same errors. It doesn't let me run jekyll build still. 

Perhaps I should just drop the pages-gem altogether?

**Comment by parkr** [comment]
> So is there a good workflow for building plugins locally and then pushing the built static pages to gh-pages?

@prufrock123 Yes, I would create my plugin as a gem, probably via `bundle gem <plugin-name>`. In my site, I'd add a line to the `Gemfile` with `gem "<plugin-name>", path: "../<plugin-name>" # or wherever this is stored on your computer`. Then, when you run `DISABLE_WHITELIST=true bundle exec jekyll serve` and you have your plugin specified in `gems` in your `_config.yml`, you will see your plugin run. Modify your plugin as you normally would inside its own directory, then re-run `jekyll serve` like above. That should do it for you!

**Comment by prufrock123** [comment]
ok awesome! Thanks so much for the help and your patience!  Very much appreciated.
