### ISSUE TITLE
Gem::InstallError on Windows 

### ISSUE THREAD

**Issue by jwillmer** [github/pages-gem#292]
I try to install `pages-gem` on a windows pc but I get the following error:

```
Gem::InstallError: nokogiri requires Ruby version < 2.3, >= 1.9.2.
```

I googled and nokogiri is compatible with Ruby and Windows (x64) in the [current pre release](https://github.com/sparklemotion/nokogiri/issues/1456#issuecomment-206481794) (`gem install nokogiri --pre`) but I don't know what I need to do in order to reference the latest nokogiri version while installing.

Can someone help me?

**Comment by parkr** [comment]
Hey! It looks like you have a version of Ruby installed that isn't compatible. When you run `ruby --version`, you'll see your installed version of Ruby.

**Comment by jwillmer** [comment]
I found a solution and made a blog post about it: [How to install Jekyll and pages-gem on Windows (x64)](http://jwillmer.de/blog/tutorial/how-to-install-jekyll-and-pages-gem-on-windows-10-x46)
