### ISSUE TITLE
Upgrade Kramdown to v1.11.0

### ISSUE THREAD

**Issue by chaosdefinition** [github/pages-gem#293]
The release of Kramdown v1.11.0 contains a crucial bug fix of syntax-highlghting, which will make some JavaScript syntax-highlighters work again, like [PrismJS](http://prismjs.com). They depend on the CSS class `language-*` in element `<pre>` to function, while switching to Rouge removed this feature.

**Comment by parkr** [comment]
Can't promise if/when we'll upgrade but I started the process of evaluating it. Thanks!

**Comment by Vugario** [comment]
+1 on this :)

**Comment by benbalter** [comment]
Fixed via https://github.com/github/pages-gem/issues/294.
