### ISSUE TITLE
Upgrade Rouge to v1.11.0

### ISSUE THREAD

**Issue by japj** [github/pages-gem#296]
The release of Rouge 1.11.0 fixes existing and adds support for a ton of new languages, see also https://github.com/jneen/rouge/blob/v1.11.0/CHANGELOG.md

**Comment by benbalter** [comment]
Thanks @japj! I can't make any guarantees, but I opened https://github.com/github/pages-gem/issues/297 for the Pages team to review the changes.

**Comment by sczerwinski** [comment]
I would like to suggest using rouge **v1.11.1**, which is the only one, I was able to highlight Kotlin syntax with.

**Comment by japj** [comment]
@sczerwinski although the rouge change log doesn't mention it, it seems Kotlin syntax was added in v1.11.1

**Comment by japj** [comment]
@benbalter there also seems to be rouge 2.0.x now, I don't know if that might be even better.

**Comment by parkr** [comment]
Rouge 2.0 requires a bump in Jekyll, so we are unable to use it at this
time.
-- 
Parker

**Comment by mjclemente** [comment]
Also adding my vote for v1.11.1 - it added cfscript support.

**Comment by SirIle** [comment]
Hi, should a new issue be created for Rouge 2.0.5 upgrade or is it already on the roadmap? It looks like they're rapidly adding languages there (https://github.com/jneen/rouge/blob/v2.0.5/CHANGELOG.md)

**Comment by DirtyF** [comment]
@SirIle see https://github.com/jekyll/jekyll/pull/5230
