### ISSUE TITLE
Github pages occasionally truncates generated page

### ISSUE THREAD

**Issue by norbertpotocki** [github/pages-gem#298]
Hi,

I found a significant inconsistency between pages generated locally and pushed to github which I can't explain. Long story short - some pages are being truncated when published to github. At the same time they work perfectly on a local jekyll installation. I hope you can help me find the root cause. Let me know how can I help more in resolving this.

### This issue affects

- [YES] The site generated by GitHub Pages
- [NO] Building sites locally

### What did you do (e.g., steps to reproduce)
- install ruby 2.3.1 using rbenv (also tried with 2.1.7-github1 - same result)
- install jekyll as per https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
- clone the repo: https://github.com/cfg4j/cfg4j.github.io
- run jekyll: bundle exec jekyll serve --config _config.yml
- open: http://localhost:4000/releases/release_4_4_0/ and scroll to the very bottom of the page
- open: http://www.cfg4j.org/releases/release_4_4_0/  and scroll to the very bottom of the page
- see how the hosted page is malformed

It's even more severe for this page (95% of the content is missing):
http://www.cfg4j.org/releases/latest/
vs.
http://localhost:4000/releases/latest/

### What did you expect to happen?
I expected both sites to look identically.

### What happened instead?
The hosted (github pages) page misses large chunks of html.

### Additional information

* Link to the live site (if applicable): http://www.cfg4j.org/releases/release_4_4_0/
* Link to the source repo (if applicable):
--- https://raw.githubusercontent.com/cfg4j/cfg4j.github.io/master/_posts/releases/2016-05-07-release_4_4_0.md
--- layout for this page: https://github.com/cfg4j/cfg4j.github.io/blob/master/_layouts/release.html

**Comment by TWiStErRob** [comment]
@parkr this can be closed. See Phlow/feeling-responsive#98 for details, the problem was with the [compress layout](http://jch.penibelst.de/) used by the feeling-responsive. The file was accidentally formatted and therefore became syntactically invalid Liquid code which messed up the generated HTML. The issue only came up when `JEKYLL_ENV=production` because of compress' configuration.

**Comment by parkr** [comment]
Thanks, @TWiStErRob. The `compress` layout has caused a couple of issues I have seen recently.
