### ISSUE TITLE
Proposal to add jekyll-get

### ISSUE THREAD

**Issue by andrewbanchich** [github/pages-gem#310]
I would really love to be able to make GET requests so that Jekyll can have some more flexibility in connecting with outside sources of JSON data. [jekyll-get](https://github.com/18F/jekyll-get) seems to do this. Any chance GitHub could officially support it?

**Comment by benbalter** [comment]
@andrewbanchich I don't know that we're going to be able to support Jekyll GET on GitHub Pages right now (although it looks like a cool plugin). There are a few reasons for this:

1. It's not packaged as a Ruby Gem, but rather, using the old `_plugins` folder structure which requires copying arbitrary Ruby into your repository

2. It does not appear to have any automated tests to ensure subsequent updates don't break existing functionality.

3. It relies on `open-uri` which can lead to unsafe and unintended network connections

4. It could potentially be used as an attack vector, if a user could ask that the GitHub Pages server call a malicious endpoint.

**Comment by parkr** [comment]
@andrewbanchich I know it's not as easy, but the alternative I would take is to have this as a pre-generation step. For example, in the `jekyll/jekyll` repo, we pull in a number of pages of site content and copy it into our source (`site/` in our case). You could pull it down into a `_data` file and it would be no less updated than if you used jekyll-get 😄
