### ISSUE TITLE
The site generated by GitHub Pages is broken

### ISSUE THREAD

**Issue by edap** [github/pages-gem#311]
I had a jekyll website that was working. Some days ago I've experienced this bug:
https://github.com/github/pages-gem/issues/181
I've first tried to use the gemfile suggested in the last comment of that issue:

```ruby
source 'https://rubygems.org'
gem 'activesupport', '4.2.7'
gem 'github-pages'
```

But the build was still broken, so I've used this Gemfile

```ruby
source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)
gem 'activesupport', '4.2.7'
gem 'github-pages', versions['github-pages'], group: :jekyll_plugins
```

and installed ruby 2.1.7 as read here https://pages.github.com/versions.json, and using https://github.com/parkr/ruby-build-github as suggested in the readme.

I've set up .travis.yml file as follow:

```yml
language: ruby
rvm: 2.1.7
script: "bundle exec jekyll build"
```

It works locally and the build on travis is green, but I still continue to receive the mail "Page build failure" every time i push and there is no way to have an error message.

my repository is https://github.com/edap/edap.github.com

Any idea?

**Comment by benbalter** [comment]
@edap the contents of your Gemfile simply governs local builds and should not cause your build to fail on GitHub Pages. Would you mind [getting in touch with GitHub support](https://github.com/contact) so that we can look at your particular repository a bit more closely?

**Comment by edap** [comment]
I've already opened an issue also in the support form that you are linking. Let me know if I can give you other information
