### ISSUE TITLE
Rouge dependency doesn’t correctly syntax highlight ES6 string interpolation

### ISSUE THREAD

**Issue by kapowaz** [github/pages-gem#318]
The `rouge` dependency set by `github-pages` is at v1.11.1, which doesn’t include more recent fixes that enable supporting ES6 syntax highlighting. This means that for example:

```javascript
return `${firstName} ${lastName}`;
```

…will highlight the backticks as errors.

**Comment by benbalter** [comment]
Thanks @kapowaz. This is dependent and somewhat duplicative of https://github.com/jekyll/jekyll/pull/5230. Once Rouge 2.x is supported upstream, we can update the dependency here.
