### ISSUE TITLE
v79 breaks Liquid conditionals

### ISSUE THREAD

**Issue by ndarville** [github/pages-gem#322]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (either `gem update pages-gem` or `bundle update pages-gem`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

* * *

Upgrading `github-pages` from v78 to v79 for my project, hafniatimes/hafniatimes.github.io, causes the front page’s CSS to bug out.

This suddenly happened on the website, hafniatimes.com, which lead me to think that some external update had broken it without my involvement instead of a local change. Turns out that seems to be the case.

The broken part of the front page is built from `_layouts/default`:

```liquid
<body{% if page.section == "frontpage" %} id="frontpage"{% endif %}>
```

#### v78 ####

```sh
git clone github.com:hafniatimes/hafniatimes.github.io repo
cd repo
bundle install
# jekyll serve
```

#### v79 ####

```sh
# Change jekyll-pages version from 78 to 79
bundle install
# jekyll serve
```

### Diff ###

```sh
$ diff index.v78.html index.v79.html 
```

```diff
25,26d24
<         <link rel="shorturl" href="http://hafnia.co/" />
< 
81,89d78
<             <link
<                 rel="alternate"
<                 hreflang="da"
<                 href="/da/"
<             />
<             <meta property="og:locale:alternate" content="da" />
< 
< 
< 
106a96,97
>         <meta property="og:type" content="article" />
> 
118c109
<     <body id="frontpage">
---
>     <body>
```

The front-page specific CSS is therefore not loaded, which causes the discrepancy.

I can’t infer from the v79 changelog which part is causing the problem, alas. Seems weird that Liquid conditionals would break like that, though; hope you can make more sense of it than I.

### Additional information

* Link to the live site (if applicable): https://hafniatimes.com
* Link to the source repo (if applicable): https://github.com/hafniatimes/hafniatimes.github.io

cc hafniatimes/issues#22

**Comment by DirtyF** [comment]
@ndarville tested this with v96 and it works fine as long as you replace section by layout (there is no section in [your index.html](https://github.com/hafniatimes/hafniatimes.github.io/blob/master/index.html#L2)

`<body{% if page.layout == "frontpage" %} id="frontpage"{% endif %}>`

**Comment by ndarville** [comment]
It seems to inherit from `_layouts/frontpage.html`, but it’s been so long since I wrote the code that I can’t remember whether Jekyll still supports this behaviour—or whether it just worked by accident at the time I first wrote it..

**Comment by pathawks** [comment]
Jekyll use to merge layout data into page data, but does not any more.

Instead of `page.section` you must now use `layout.section` to access that data.

**Comment by ndarville** [comment]
Appreciate it, cheers.
