### ISSUE TITLE
Add jekyll-hyphenate

### ISSUE THREAD

**Issue by adrientetar** [github/pages-gem#326]
It would be nice to add support for hyphenation of text at build-time:

https://github.com/grzm/jekyll-hyphenate_filter

**Comment by benbalter** [comment]
What's the advantage to using the plugin. Can't you accomplish the same via CSS?

**Comment by adrientetar** [comment]
> What's the advantage to using the plugin. Can't you accomplish the same via CSS?

Well the thing is, browser support is [inconsistent](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#Browser_compatibility) &ndash; Chrome and Opera don't support automatic hyphenation at all.

**Comment by benbalter** [comment]
While I'm a big fan of proper typography, when we're looking at over a million sites, I don't know that this is the most important problem we should be solving right now, and am going to close this in favor of focusing on some higher-impact features. Thanks @adrientetar!
