### ISSUE TITLE
localhost website pointing to remote git repository

### ISSUE THREAD

**Issue by Socapex** [github/pages-gem#327]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (either `gem update pages-gem` or `bundle update pages-gem`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)
Followed this guide: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/

### What did you expect to happen?
Get a working local copy of a jekyll site.

### What happened instead?
No CSS. Links broken. Headaches.

### Additional information

If you follow the guide step-by-step, at Step 4: Build your local Jekyll site you will try to preview your locally served site. The css doesn't work, as it tries to fetch it remotely. I have not been able to set my urls in a way that uses local main.css. Further-more, new pages try to open on my github repo instead of locally. This happens even if my site.url is empty. Somehow github-pages always assumes you are working remotely.

This also brings up the question, does github-pages enforce using remote css because we are not allowed to edit the theme?

Problem: 
<img width="1440" alt="screenshot 2016-10-03 22 33 33" src="https://cloud.githubusercontent.com/assets/156883/19060849/af0afd5e-89b9-11e6-90b6-c69a98365fc7.png">
<img width="1440" alt="screenshot 2016-10-03 22 39 53" src="https://cloud.githubusercontent.com/assets/156883/19060944/7ab913fa-89ba-11e6-92e5-c968353c7a19.png">

**Comment by DirtyF** [comment]
This should be fixed in next release when Jekyll is updated to 3.3 version. See https://github.com/jekyll/jekyll/pull/5431

**Comment by Socapex** [comment]
Ok, thank you for the theme override link. Good day.
