### ISSUE TITLE
Proposal: Add amp-jekyll 

### ISSUE THREAD

**Issue by citrusui** [github/pages-gem#355]
[Link to plugin](https://github.com/juusaw/amp-jekyll)

This plugin enables you to generate AMP versions of your Jekyll posts alongside the normal HTML posts. AMP pages load super fast, especially on older mobile devices.

While it is possible to only write posts in AMP (I've tried), you cannot use your own JavaScript or tags like `<form>` which aren't supported. Yes, the page may load fast by default, but it loses lots of functionality when using a desktop (hence the name Accelerated *Mobile* Pages).

**Comment by LewisLebentz** [comment]
Interested in this plugin too.

**Comment by benbalter** [comment]
I wouldn't be opposed to adding AMP support, especially if it was automatic and transparent (e.g., just activate the plugin and it works), similar to how Jekyll Feed, Jekyll Sitemap, etc. work. 

Regardless of the implementation, we wouldn't be able to consider any plugin without unit and integration tests for the desired behavior.

**Comment by mbirth** [comment]
Related: https://github.com/jekyll/jekyll/issues/3041

**Comment by benbalter** [comment]
> I wouldn't be opposed to adding AMP support, especially if it was automatic and transparent (e.g., just activate the plugin and it works), similar to how Jekyll Feed, Jekyll Sitemap, etc. work.
>
> Regardless of the implementation, we wouldn't be able to consider any plugin without unit and integration tests for the desired behavior.
