### ISSUE TITLE
Installing github-pages via gem

### ISSUE THREAD

**Issue by tomtomklima** [github/pages-gem#358]
- [ ] The site generated by GitHub Pages
- [x] Building sites locally

I tried to install via execute: 
> gem install github-pages

And it is unable to resolve dependencies: github-pages-health-check requires public_suffix (~> 1.4); addressable requires public_suffix (>= 2.0.2, ~> 2.0). 

Currently running 64bit Mint v17.3 with gems v.1.8.23

**Comment by parkr** [comment]
We recently upgrade github-pages-health-check to use the latest version so you should be good to go! 😄
