### ISSUE TITLE
 just the README.md is appearing in my blog site

### ISSUE THREAD

**Issue by jlopezfisica** [github/pages-gem#369]
I just started using a theme for a git-hub blog. I added two .md files in my repository but just the README.md file is appearing in my git-hub blog.

This is my site:

https://jlopezfisica.github.io/google_summer_of_code_univeristy/

How can I add more posts in my site?

In the original blog from git-hub by @jldec he said that just adding more .md will add more pages.

**Comment by benbalter** [comment]
@jlopezfisica per [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#questions), please direct all GitHub Pages support requests to https://github.com/contact.
