### ISSUE TITLE
Regression on Github pages since November 30th

### ISSUE THREAD

**Issue by vincent-zurczak** [github/pages-gem#372]
### Before submitting an issue, please be sure to

- [  **DONE** ] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [   **DONE** ] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [  **x**  ] The site generated by GitHub Pages
- [ **x** ] Building sites locally

### The story...

We have a web site hosted by Github pages, and generated with Jekyll.
The source repository can be found [here](https://github.com/roboconf/roboconf.github.io).

On Friday evening, I pushed an important update.
Few seconds later, I received the following email.

```
The page build failed with the following error:

A file was included in `/_layouts/page.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

I checked many things:

- I had already built locally (with success).
- I took a look at our [Travis build](https://travis-ci.org/roboconf/roboconf.github.io). We use **html-proofer** to make sure there is no broken link on our generated web site. We also have a custom Ruby script that verifies assertions on our source pages. The build passed with success.
- Jekyll's **safe** parameter was set to `true` in our configuration. Using `--safe` did not change anything locally. It keeps on working.
- I cleared all my local gems and started from the last versions. I now use **github-pages** version 111.
- I rebuilt and revalidated everything locally. It builds and it works.
- I pushed these changes to Github and the Travis build still works with the last GP version. So, nothing related to symlinks or specific to my machine. And still, I keep on receiving the same build failure message.
- I then made a backup of my web site and **rewrote** the history ( :fearful: ). The [last commit](https://github.com/roboconf/roboconf.github.io/commit/595ce2c806f0d07a8316c4793ffe99476c224aa3) was successfully pushed to our web site on November 30th. Today, the exact same commit failed.
- I have just readded my last changes. Still in error.

Clearly, there is a regression with Github pages.
I did not find any documentation mentioning a major upgrade. I saw **relative-links** were added, as well as some other dependencies. Maybe this can explain that.

Anyway...

* There is a regression. My commit from November 30th should have been validated when I pushed it back today.
* And/or it should behave the same locally and on Github.
* Last but not least, the error message about symlinks is not clear enough. I have not found in which project / Git repository this should been pushed. It is not in Jekyll. A pointer about this could help so that I can submit an issue. :question:

**Comment by benbalter** [comment]
@vincent-zurczak I believe you need to wrap [this line](https://github.com/roboconf/roboconf.github.io/blob/master/_layouts/page.html#L68-L69) with a `{% if page.menus %}` block. I suspect at least one page does not have a menu, hence the message:

> A file was included in `/_layouts/page.html` that is a symlink or does not exist in your `_includes` directory.

> And/or it should behave the same locally and on Github.

Have you followed [these instructions](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) (specifically, regaridng your Gemfile and the `:jekyll_plugins` group)?

**Comment by vincent-zurczak** [comment]
Hi @benbalter.

I had missed the **jekyll_plugins** thing (my Gemfile was quite old).
I updated my Gemfile to...

```
source 'https://rubygems.org'

gem 'html-proofer', '>=3.0'
gem 'github-pages', group: :jekyll_plugins
```

Indeed, there is now an error locally.

```
Liquid Exception: Could not locate the included file 'menu..html' in any of ["/home/vzurczak/workspaces/roboconf/roboconf.github.io/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/page.html
```

I will follow this lead (my best one since last week). Many thanks! :smiling_imp: 
I will keep you informed and close this issue if or when solved.

**Comment by vincent-zurczak** [comment]
You were right. One of our MD file had no layout.
And **Jekyll Default Layout** picked one, hence the error. Many, many thanks for your help. :+1:
