### ISSUE TITLE
Proposal to add jekyll-babel

### ISSUE THREAD

**Issue by khilnani** [github/pages-gem#375]
I'd like to request adding for support https://github.com/babel/jekyll-babel as a whitelisted plugin. Ideally, if Jekyll-Assets #189 were included, it would make this request redundant , but it's unclear if there are specific concerns with Jekyll-Assets due to it's larger set of features. jekyll-babel is focused on es6 javascript.

jekyll-babel is similar on jekyll-coffeescript and has the similar requirements for execjs in addition to babel specific gems:

- jekyll-babel - https://github.com/babel/jekyll-babel
- babel-transpiler / babel-source - https://github.com/babel/ruby-babel-transpiler

Thanks!

**Comment by khilnani** [comment]
This may be slightly more needed with the upcoming updates from Chrome

Warning in Chrome: "Fetching scripts with an invalid type/language attributes is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5760718284521472 for more details."

**Comment by benbalter** [comment]
> This may be slightly more needed with the upcoming updates from Chrome

Can you explain what you mean?

**Comment by khilnani** [comment]
Chrome's update warns against using script tags with invalid types, eg. `<script type="text/babel" src="/js/global.jsx"></script>` is invalid. The Babel javascript library allows transpile ES6 to javascript offline and in the browser. The browser approach uses the tag thats soon going to be invalid. 

After this goes into effect, if a developer wants to use ES6 in general, or JSX for React , he/she has 2 options:

1.  Insert the entire JS into the HTML file in a script tag   without any minification - bloats the HTML and still doesn't support full ES6 (eg. export/import). eg.
```
<script type="text/babel">
const js = "Full App's ES6 JS here, could be a 1000s of lines long with a lot of whitespace";
</script>
```

2. Process offline via the assets or babel plugin that converts to a regular JS file that can be linked to as an external script. eg.
```
<script type="text/javascript" src="/js/compiled.js"></script>
```

No one would use option 1 unless they really really had or wanted to, or of the site was very very simple. The second option is the desired one, since it would utilize the full feature set of the offline JS processing tools just as one would use Grunt,Gulp and allow the page to be built with external scripts.

Hopefully that helps a bit, thanks!!!

**Comment by khilnani** [comment]
Basic use case similar to coffeescript, but the standards oriented version. The babel plugin takes care of handling ES6/E2015, ES7/2016 to valid browser JavaScript. At this point, supporting babel more a lot more sense to be than supporting coffee script (jekyll-coffee is whitelisted). Most code schools teach new students more about ES6/7 than CoffeeScript today.

**Comment by benbalter** [comment]
@khilnani thanks for opening the issue at starting the conversation. At this time, I don't think we're in a position to support this, although we've received several requests for this internally as well. As a hosted service, unlike a distributed project, we don't have the luxury of regular major bumps and breaking changes. When we add support for a new converter, we have to support it in perpetuity. Jekyll jumped on the CoffeeScript train when it was relatively widely adopted, and even though it's not as widely used, we still must continue to maintain and support it. Given the volatility and various flavorous / levels of support right now, I'd rather be a later adopter here, than an earlier adopter, so that if we have to support something going forward, we know we're supporting the new standard, not the latest standard.

**Comment by khilnani** [comment]
Understand. Thanks for considering  and following up! @benbalter

**Comment by eokoneyo** [comment]
I know it might be considered bad form to start a conversation on an already closed ticket but I didn't want to have to open a new one when we can just continue the conversation here. 

I understand why the team might not have been interested in supporting ES6 then, but its pretty much a standard right now, also it'd be really helpfully if this gets added as a supported plugin.
