### ISSUE TITLE
Incompatibility with Ruby 2.4.0

### ISSUE THREAD

**Issue by sathomas** [github/pages-gem#376]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [X] Building sites locally

### What did you do (e.g., steps to reproduce)

Ruby version 2.4.0

Gemfile:

```
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
```

`bundle install`

### What did you expect to happen?

Gems should be installed

### What happened instead?

```
An error occurred while installing json (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

**Comment by parkr** [comment]
Hey! Thanks for reporting this issue. I hit this last night myself. The issue appears to be that the `json` gem won't compile on Ruby 2.4. https://github.com/flori/json/issues/303

I will try to take a look this week. It appears upgrading from json 1.x to json 2.x would solve the issue. We can see what exactly is depending on this gem and pass along the request to update and update it here as well.

**Comment by mjsteinbaugh** [comment]
I'm also seeing this on multiple macOS machines. The problem has to do with json 1.8.3 failing to build on ruby 2.4.0p0.

**Comment by parkr** [comment]
It appears we depend on activesupport which depends on json 1.x. We should see if the Rails team is willing to release a new 4.2.x which bumps the json dependency (or removes it).

**Comment by julou** [comment]
glad to see it's already on your radar! this makes my first contact with gh-pages rather painful :(

and?… is there any workaround to set up a gh-pages site locally with jekyll on macOS in the meantime?

**Comment by DirtyF** [comment]
@julou I recommend you use rbenv with Ruby 2.3.1 and github-pages gem.

**Comment by nickmccurdy** [comment]
Note that you can `brew install rbenv`, it will give you suggestions on how to set it up for your shell. 😄

**Comment by georgeperez** [comment]
There's additional instructions in their [repo](https://github.com/rbenv/rbenv).

**Comment by julou** [comment]
awesomely fast! thank you so much.
for others, here's a step-by-step:

1. install rbenv (using an admin account)
```
brew install rbenv
```

2. install ruby 2.3.1 and corresponding gems (stored in ~/.rbenv)
```
rbenv init
rbenv install 2.3.1
gem install bundler
```

3. now in you gh-pages directory
```
# cd my-gh-pages-site
bundle install
```

but I can't get `rbenv init` to add ~/.rbenv/shims to my PATH!?!  
Looks like I have to add `export PATH=~/.rbenv/shims:$PATH` or `export RBENV_VERSION=2.3.1` in my .bashrc  
Am I missing something obvious?

**Comment by DirtyF** [comment]
* run `rbenv rehash` to rehash your shims after install (https://github.com/rbenv/rbenv#rbenv-rehash)
* add `eval "$(rbenv init -)"` in your `.zshrc` or `.bashrc`

**Comment by julou** [comment]
thx!  👍

**Comment by parkr** [comment]
It appears they're working on activesupport fixes for Ruby 2.4 here: https://github.com/rails/rails/pull/27473

**Comment by mjsteinbaugh** [comment]
Using `rbenv` with ruby 2.3.1 works on macOS 10.12.2:

Install `rbenv` first with Homebrew:

```{bash}
brew install rbenv
```

Now modify your `~/.bash_profile`:

```{bash}
export PATH=~/.rbenv/shims:$PATH
eval "$(rbenv init -)"
```

Finally, install ruby 2.3.1 and the `github-pages` gem:

```{bash}
rbenv install 2.3.1
rbenv versions
rbenv global 2.3.1
rbenv rehash
gem install bundler
gem install github-pages
```

**Comment by bigeagle** [comment]
1/3 a year has passed, but the solution to this issue is still: go back to ruby 2.3

**Comment by parkr** [comment]
@bigeagle I am able to run Jekyll on 2.4. Can you help provide more details?

**Comment by cveneziani** [comment]
The Rails team released a new version of activesupport (v4.2.8). Bumipng this gem should solve the incompatibility with ruby 2.4.

**Comment by parkr** [comment]
I'm able to run `bundle install` with Ruby 2.4.1 locally without any modifications to this repository. Can anyone confirm?

**Comment by bigeagle** [comment]
It worked, finally.

**Comment by parkr** [comment]
Great to hear!

**Comment by adamralph** [comment]
Still doesn't work for me with Ruby 2.4. I get errors with yajl-ruby v 1.2.1. Apparently, yajl-ruby 1.3.0 needs to be used with Ruby 2.4.

**Comment by parkr** [comment]
yajl-ruby 1.2.2 works fine with Ruby 2.4. Please `bundle update yajl-ruby` or run `gem install yajl-ruby -v 1.2.2`.
