### ISSUE TITLE
Can't create a Github Page for my repo

### ISSUE THREAD

**Issue by ronakdev** [github/pages-gem#378]
I tried to make a github page for my repo, [100days](https://github.com/ronakdev/100days), but after choosing a theme (Cayman), it wouldn't redirect me to the usual "select your content from your markdown" page. 

Is this a bug, or the new way Github Pages is working?

**Comment by benbalter** [comment]
@ronakdev Per [the contributing guidelines](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#where-to-get-help-or-report-an-issue), please contact [GitHub Support](https://github.com/contact).
