### ISSUE TITLE
Use latest kramdown version

### ISSUE THREAD

**Issue by PowerSnail** [github/pages-gem#379]
Kramdown has fixed a bug where CDATA is inserted incorrectly, in its latest version (1.13.1). However, Github-pages currently require kramdown 1.0.2. Some equation blocks are not rendered as a result. 

For example, on this page: [Apple Box](https://powersnail.github.io/2017/apple-box/), there is an `align*` block missing (right above "Thus, we can return ...".

Is it possible to work around this limit, and force github-pages to use the latest version of kramdown?

Thank you!

**Comment by benbalter** [comment]
Thanks @PowerSnail! Closing in favor of #334. It's on our wish list. There's a few changes in terms of how Markdown is handled that we need to explore to avoid breaking changes, but it's definately something we'd like to see, time permitting.
