### ISSUE TITLE
"No GitHub API authentication" error

### ISSUE THREAD

**Issue by tomjohnson1492** [github/pages-gem#399]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)

Add this into the Gemfile:

```
source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins
```

Run `bundle update` and `bundle exec jekyll serve`. 
Make a small edit to a file. 
When Jekyll auto-rebuilds, an error appears in the Terminal that says "GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data."

### What did you expect to happen?

I did not expect that Github Metadata error to appear.

### Additional information

When I removed the Gemfile, the error went away. Since this is the only gem outside of Jekyll that I'm using in my project, I suspect the error has something to do with github-pages. That's why I'm filing an issue here.

I fixed the issue by following the resolution described [here](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_install_jekyll_on_mac.html#githuberror). This removed the error from occurring. 

I just wanted to report this error in case there's something with the github-pages gem that is causing it.

**Comment by parkr** [comment]
Hey @tomjohnson1492! This is expected. The jekyll-github-metadata gem is automatically enabled for GitHub Pages builds (including builds using this gem locally). It pulls in information from the GitHub API, but [first checks the environment for authentication, which is required for some API calls to return the data we want](https://github.com/jekyll/github-metadata/blob/8906f2b9c890f0aafef96423c7cd7e5047f7dae4/lib/jekyll-github-metadata/client.rb#L96-L97). It's a warning, not an error, so you should be good to ignore them locally. 👍

**Comment by SeanKilleen** [comment]
@parkr I think the issue here is that it appears to break Jekyll's watch functionality. 

E.g, in the scenario described above, which I'm also hitting, I have the following:

### Repro
* Setup the gemfile as described above
* run `bundle exec jekyll serve` (which watches for changes and regenerates each time)
* make a change to a file and save
* See the "warning" errors

### Expected behavior
The files are still generated on each change and we can ignore the errors.

### Actual behavior
The jekyll pipeline is broken. The file changes are not actually processed, because jekyll perceives an error to have happened during generation.

Instead, we are required to force-quit jekyll and run `bundle exec jekyll serve` each time.

Does this help clarify the issue? If so, it would be awesome to open this up for a second look.

**Comment by coin8086** [comment]
I have the same problem with the new version of github-pages (136) on jekyll (= 3.4.3). It breaks the common dev flow locally, that is the convenient edit-and-refresh way. So I hope it will be fixed soon.

**Comment by asnowfix** [comment]
The work-around described above does not work for me. I am using a GitHub Enterprise instance & tried using a personal access token generated by GHE & a one generated by GH.com. None worked & I am still getting the error message at each refresh:

```
      Regenerating: 1 file(s) changed at 2017-05-16 12:27:51 ...error:
             Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
             Error: Run jekyll build --trace for more information.
```

Despite the hint above, `$ jekyll build --trace --watch`  does not give anything more useful:

```
      Regenerating: 1 file(s) changed at 2017-05-16 12:25:13 ...error:
             Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
             Error: Run jekyll build --trace for more information.
```

**Comment by asnowfix** [comment]
Fixed my issue (not saying it is yours) by adding...

```ruby
github: [metadata]
```

...to `_config.yml`

**Comment by whizzzkid** [comment]
fix by @asnowfix works :) thanks :+1:

**Comment by abhishekp1996** [comment]
A ton thanks to @asnowfix 
The fix works very well.

I need to point out, add the code as it is. `[metadata]` will be automatically pulled by the generator.

**Comment by fgreve** [comment]
Thanks to @asnowfix

**Comment by super456** [comment]
@asnowfix 
I'm very grateful to you ！:smile:

**Comment by john20xdoe** [comment]
as per @asnowfix fix, this results in a missing site.title (blank values?). but other wise the site was being served locally successfully.

**Comment by wrschneider** [comment]
thanks @asnowfix, this was driving me crazy.

**Comment by karamfd** [comment]
@asnowfix Your solution is working perfectly for me as well. Thank you very much 😃

**Comment by troccoli** [comment]
Thank you @asnowfix . Worked for me too.

**Comment by seanlerner** [comment]
@asnowfix solution didn't work for me.

I ended up generating a token and putting it in my env:

Generate token: https://github.com/settings/tokens

Run:

```bash
JEKYLL_GITHUB_TOKEN=<your token> jekyll serve
```
Or you can add to your shell config file:

```bash
#  .zshrc, .bashrc or .bash_profile

export JEKYLL_GITHUB_TOKEN=<your token>
```

Then in terminal:

```bash
source ~/.zshrc
```
