### ISSUE TITLE
Markdown anchors inconsistent between repo page and gh-pages

### ISSUE THREAD

**Issue by benpetty** [github/pages-gem#410]
- [X] The site generated by GitHub Pages
- [ ] Building sites locally

### What did you do (e.g., steps to reproduce)

Selecting a Github Pages theme and automatic deployment in my repo's settings, I found that the markdown anchor tags generated in my README headings are inconsistent between the repo page and the gh-pages deployment

### What did you expect to happen?

Include `_` in anchor url, (it works on the repo page this way)

For example: [https://github.com/benpetty/data-structures#linked_listpy](https://github.com/benpetty/data-structures#linked_listpy) is a valid anchor tag url on the repo page, because there is an h2 heading `## **linked_list.py**`. I expected it to behave the same way on the github pages rendering.

### What happened instead?

Github Pages theme renders the tag differently, removing the `_` from the anchor's id.

- Valid: [https://benpetty.github.io/data-structures/#linkedlistpy](https://benpetty.github.io/data-structures/#linkedlistpy)
- Invalid: [https://benpetty.github.io/data-structures/#linked_listpy](https://benpetty.github.io/data-structures/#linked_listpy) 

...breaking the generated link from the README table of contents.

markdown:
`## **linked_list.py**`

repo html : 
`<h2><a id="user-content-linked_listpy" class="anchor" href="#linked_listpy" aria-hidden="true">...`

gh-pages html:
`<h2 id="linkedlistpy"><strong>linked_list.py</strong></h2>`

### Additional information

* Link to the live site (if applicable):
[https://benpetty.github.io/data-structures/](https://benpetty.github.io/data-structures/)

* Link to the source repo (if applicable):
[https://github.com/benpetty/data-structures](https://github.com/benpetty/data-structures)

**Comment by benbalter** [comment]
I believe https://github.com/github/pages-gem/pull/400 may fix this.

**Comment by parkr** [comment]
We just upgraded to the latest version of kramdown. @benpetty would you please re-confirm?

**Comment by benpetty** [comment]
@benbalter @parkr Fixed! Thank you!!
