### ISSUE TITLE
[question] Whitespace control and liquid-4.0.0

### ISSUE THREAD

**Issue by yalov** [github/pages-gem#411]
I am assuming `gem github-pages` v120 have liquid-3.0.6 without cool [Whitespace control].(https://help.shopify.com/themes/liquid/basics/whitespace)

Give some info about when github-pages will have liquid-4.0.0 with Whitespace control.

**Comment by DirtyF** [comment]
https://github.com/jekyll/jekyll/pull/4362 has been merged into Jekyll master branch, you can help test Liquid 4, to ship this in next Jekyll version and then to GitHub Pages 💎

**Comment by benbalter** [comment]
What @DirtyF said. We're blocked here until Liquid 4 is supported in Jekyll core (and then can be expected to update 1-2 months after).
