### ISSUE TITLE
Upgrade jekyll-sitemap?

### ISSUE THREAD

**Issue by kvz** [github/pages-gem#412]
When installing the latest [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes) theme `4.2.1`, `bundler` throws:

```
   Bundler could not find compatible versions for gem "jekyll-sitemap":
     In snapshot (Gemfile.lock):
       jekyll-sitemap (= 0.12.0)

     In Gemfile:
       github-pages (= 112) was resolved to 112, which depends on
         jekyll-sitemap (= 0.12.0)

       minimal-mistakes-jekyll (= 4.2.1) was resolved to 4.2.1, which depends on
         jekyll-sitemap (~> 1.0)
```

It appears the github-pages gem that I use for bootstrapping jekyll, wants `jekyll-sitemap (= 0.12.0)` but minimal-mistakes-jekyll wants `jekyll-sitemap (~> 1.0)`.

The latest version of github-pages (120) still requires the old jekyll-sitemap version: https://rubygems.org/gems/github-pages/versions/120.

Any chance to losen the dependency on jekyll-sitemap?

Reported also in https://github.com/mmistakes/minimal-mistakes/issues/842

**Comment by pathawks** [comment]
See #409

**Comment by kvz** [comment]
Ah perfect! I'll just wait on the next release then, thank you for the quick response!
