### ISSUE TITLE
site.baseurl not able to set to string.empty

### ISSUE THREAD

**Issue by jwillmer** [github/pages-gem#419]
First of all I am not sure if this is the right place for the issue if not i am apologize. I have a jekyll theme in my repository that runs without any problem on GitHub since I devloped it but today I noticed that the links to the [generated blog](http://jwillmer.github.io/jekyllDecent/) are all broken. Did something in the engine changed?

This is how I define a link:
```
<link rel="stylesheet" href="{{ "/css/screen.css" | prepend: site.github.url | prepend: site.baseurl }}">
```

and this is in my `_config`:
```
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "http://jwillmer.github.io/jekyllDecent" # the base hostname & protocol for your site. Have a look at robots.txt as well!
```

You can find the project at: [jwillmer/jekyllDecent](https://github.com/jwillmer/jekyllDecent)

**Comment by jwillmer** [comment]
I close this issue because I opened it on Jekyll: https://github.com/jekyll/jekyll/issues/5908

**Comment by benbalter** [comment]
This is now fixed. If you set your baseurl to `""` it will be respected.
