### ISSUE TITLE
bash code like $'\0' breaks syntax highlighting for rouge highlighter

### ISSUE THREAD

**Issue by selivan** [github/pages-gem#436]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)

Public a page where bash code block contains `$'\0'`(bash-specific way to use string with escaped unprintable characters):

    ```bash
    null=$'\0';
    echo all further code is highlighted as string
    ````

### What did you expect to happen?

See correct highlighting: `$'\0'` is string, characters after closing `'` are not.

### What happened instead?

All further code is displayed as string until parser stumbles upon single quote `'` character.

### Additional information

* Link to the live site (if applicable): [selivan.github.io - ansible-check-on-commit-vault-files-are-encrypted](https://selivan.github.io/2017/04/08/ansible-check-on-commit-vault-files-are-encrypted.html).
* Link to the source repo (if applicable): https://github.com/selivan/selivan.github.io

Jekyll `_config.yml`:
```
highlighter: rouge
markdown: kramdown
kramdown:
   input: GFM
```

**Comment by benbalter** [comment]
I believe this issue should be addressed upstream either in Jekyll, or more likely Rouge as it does not sound specific to GitHub Pages.
