### ISSUE TITLE
How can I add a plugin to the pages-gem bundle white-list?

### ISSUE THREAD

**Issue by untra** [github/pages-gem#438]
### Before submitting an issue, please be sure to

- [x ] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x ] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [ ] Building sites locally

### What did you do (e.g., steps to reproduce)

I maintain a plugin for building multilingual jekyll websites called [polyglot](https://github.com/untra/polyglot). It is designed to facilitate development of good i18n practices when building a blog or website that requires designated content.

It also tries to simultaneously build the website in parallel, a task that jekyll blogs (and ruby, kindof) aren't meant to tackle.

There's a lot of feature cutting aspects about this plugin:
- SEO techniques and tools
- multilingual content organization and management
- parallel website building

### What did you expect to happen?

What vetting is required to get my plugin [whitelisted](https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L20)? Is there anything I can do now to get this plugin approved to be whitelisted? will parallel builds need to be removed? Should there be greater test coverage? Does it look fine as is?

I would like to know what changes / vetting is needed to enable my plugin, **or for providing i18n structure to github-hosted jekyll website design and management.**

### What happened instead?

Multilingual websites have their own distinct requirements, and I feel it would be in jekyll's, github's, and user's interests to provide tools to address those needs. And It's in my interest to make those tools.

### Additional information

* Link to the live site (http://polyglot.untra.io):
* Link to the source repo (https://github.com/untra/polyglot):

**Comment by benbalter** [comment]
Thanks @untra! Per the contributing file:

> General GitHub Pages feature requests, including requests to add additional plugins or themes should be made [via GitHub Support](https://github.com/contact?form%5Bsubject%5D=GitHub%20Pages%20Feature%20Request).
