### ISSUE TITLE
Whitelisting gem jekyll-last-modified-at plugin gem

### ISSUE THREAD

**Issue by jimkohl** [github/pages-gem#476]
We provide a large content site for our developers, built on github-pages & GHEnterprise.

When reading content articles, it can be a challenge knowing what is stale vs current,
so having _publication date_ is helpful.

Aside of embedding a date in front matter, we'd really prefer to leverage the platform and get the last commit date from gh.

Locally I've found and am using Garin Torikian's **jekyll-last-modified-at** plugin gem and it does the job.   _https://rubygems.org/gems/jekyll-last-modified-at/versions/0.3.4_
But since its not whitelisted we can't directly use in our production site.

What are the chances that this plugin can be whitelisted?  Are there security issues or reasons why it isn't?
If it could be whitelisted, is there anything I could do to help (updating gh-pages, test cases, testing, etc)?

This would be a really nice add for many folks methinks.
Thanks for considering this!

**Comment by jimkohl** [comment]
@benbalter @parkr Hi guys, what is the process for getting plugins whitelisted?  
Is this something I can help with (even if its code I didn't write)?

**Comment by pathawks** [comment]
#119
#177

**Comment by benbalter** [comment]
Closing in favor of #119 and #117 (thanks @pathawks!). Please see those issues for prior discussions.
