### ISSUE TITLE
Images broken on commit

### ISSUE THREAD

**Issue by ferjgar** [github/pages-gem#484]
### Before submitting an issue, please be sure to

- [X ] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X ] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [X ] The site generated by GitHub Pages
- [ ] Building sites locally

### What did you do (e.g., steps to reproduce)
Commit an image.

### What did you expect to happen?
To have the right image in the repository.

### What happened instead?
In the repo the images are displayed as empty or just _semi-broken_, like if they have been uploaded wrong.

### Additional information
In my local installation everything works as expected, with the latest version of the gem (updated on 17 sept). When I commit my changes (with images), in the remote repo those appear as broken (e.g. https://github.com/ferjgar/ferjgar.github.io/blob/master/assets/img/2012-10-22-git-clone.png, http://ferjgar.rocks/assets/img/2012-10-22-git-clone.png).
Oddly enough, other images look like semi uploaded, e.g. https://github.com/ferjgar/ferjgar.github.io/blob/master/assets/img/Y8rENTj.jpg, https://github.com/ferjgar/ferjgar.github.io/blob/master/assets/img/wtf2.gif.

* Link to the live site (if applicable): http://ferjgar.rocks
* Link to the source repo (if applicable): https://github.com/ferjgar/ferjgar.github.io

**Comment by benbalter** [comment]
This does not sound like an issue with the GitHub Pages Gem. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.
