### ISSUE TITLE
Please Bump jekyll-relative-links to 0.5.0

### ISSUE THREAD

**Issue by GABeech** [github/pages-gem#486]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#where-to-get-help-or-report-an-issue).*

### What did you do (e.g., steps to reproduce)

I have a custom collection, say `_policies` with a bunch of `.md` files in it. Linking to the index using the format: `[Index](../index.md)` does not work because the 0.4.1 version of jekyll-relative-links does not support the collections option and does not attempt to parse anything outside of the `site.pages` collection. 

### What did you expect to happen?
Since the documentation for jekyll-relative-links is for 0.5.0, I would expect the current behavior with GH pages and pages-gem to match. 

### What happened instead?
Relative links inside of collections do not work. 

### Additional information

I have an issue open with GitHub enterprise Support (#50271) as well.

jekyll-relative-links is locked to [version 0.4.1](https://github.com/github/pages-gem/blob/a8101ee4e67ba88641c2df9c5c1244abad1658f1/lib/github-pages/dependencies.rb#L35), the ability to use the plugin for custom collections was introduced in version 0.5.0. 

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

**Comment by parkr** [comment]
Cool! Let's continue this in #487.

**Comment by cjerdonek** [comment]
FYI, this seems to have introduced a regression: https://github.com/benbalter/jekyll-relative-links/issues/36

In my case, a reference link after a list item stopped rendering after this change.
