### ISSUE TITLE
Jekyll 3.6.0

### ISSUE THREAD

**Issue by JakeWharton** [github/pages-gem#489]
I'm looking for [a fix](https://github.com/jneen/rouge/pull/702) in the syntax highlighter which was released in Rogue 2.2.0. Kramdown 1.14 added support for Rogue 2.x (previously it only supported Rogue 1.x). Jekyll 3.6.0 bumped Kramdown from 1.9 to 1.14. So now, humbly, I'm trying to get the last link in the chain updated.

**Comment by parkr** [comment]
Hey @JakeWharton! Please follow along for the Jekyll 3.6.0 upgrade in #474. 😄 

Once the upgrade is approved & verified, we'll update to a newer version of Rouge.

Thanks!

**Comment by JakeWharton** [comment]
Gah I looked for issues but not PRs. Thanks!

**Comment by parkr** [comment]
No sweat. Hubot has issued a PR for the Rouge 2.x update as well: https://github.com/github/pages-gem/pull/490. 🔜 , I hope!
