### ISSUE TITLE
Update Jekyll 3.6

### ISSUE THREAD

**Issue by laukstein** [github/pages-gem#491]
In 21 Sep 2017 announced Jekyll 3.6 https://jekyllrb.com/news/2017/09/21/jekyll-3-6-0-released/
and still isn't updated in GitHub Pages https://pages.github.com/versions/

> This release comes with it Rouge 2 support, but note you can continue to use Rouge 1 if you’d prefer. We also now require Ruby 2.1.0 as 2.0.x is no longer supported by the Ruby team.

GitHub Pages currently has Rouge 1.11.1, Ruby 2.4.0, Jekyll 3.5.2.

**Comment by DirtyF** [comment]
on his way in https://github.com/github/pages-gem/pull/474

**Comment by parkr** [comment]
Yes, please subscribe to those 2 pull requests as @DirtyF notes (the Subscribe button on the right hand side of each page will let you do that).

We'll handle all updates and discussion there! Thanks 😄
