### ISSUE TITLE
repo README issue

### ISSUE THREAD

**Issue by vgrand-org** [github/pages-gem#492]
### This issue affects

- [ ] The site generated by GitHub Pages
- [X] Building sites locally

### What did you do (e.g., steps to reproduce)

Read the README, tried to execute `run bundle` after pasting `gem 'github-pages', group: :jekyll_plugins` into Gemfile.

### What did you expect to happen?

gem would install.

### What happened instead?

Error message:

```
[!] There was an error parsing `Gemfile`: wrong number of arguments (given 0, expected 1..2). Bundler cannot continue.

 #  from Gemfile:3
 #  -------------------------------------------
 #    # Gems here
 >    gem github-pages, group: :jekyll_plugins
 #  end
 #  -------------------------------------------
```

### Additional information

The correct line for gemfile appears to be (though I'm not a ruby coder, this seems to have successfully installed gem, and is consistent with example gemfile code I found elsewhere):

`gem 'github-pages', :group => :jekyll_plugins`

i.e., colon before `group` instead of after, and arrow operator.  Not sure if the single quotes on `github_pages` required.

**Comment by DirtyF** [comment]
[This syntax is perfectly valid](https://github.com/bbatsov/ruby-style-guide#hash-literals) and works fine (provided you use a recent Ruby version).

**Comment by vgrand-org** [comment]
According to command line:

```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

so not sure why observing the error.

**Comment by parkr** [comment]
What is the exact command you ran? Did you use the ruby executable or something else?

**Comment by vgrand-org** [comment]
```
\curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install 2.4
rvm use ruby-2.4.1 --default
gem install bundle
bundle install
```

**Comment by benbalter** [comment]
It looks like in the err output posted, there may not be any quotes around `github-pages`?

**Comment by vgrand-org** [comment]
@benbalter yep, that seems to be it.  Tracked the error back to how I originally made file:

```
echo 'gem 'github-pages', group: :jekyll_plugins' > Gemfile
```

Must have lost track of fixing that during troubleshooting.
