### ISSUE TITLE
Demonstrate usage in github pages gem with a docs/ folder and _config.yml

### ISSUE THREAD

**Issue by philoserf** [github/pages-gem#502]
For your consideration. Create a `docs/` folder with an `index.md` and a `_config.yml` containing sufficient configuration to demonstrate use of the github-pages gem with GitHub Pages.

### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#contributing-to-the-github-pages-gem)

**Comment by parkr** [comment]
With the `docs/` folder, everything goes in that directory (it's like Jekyll changes its `source` to be `docs/` in your repository). Locally, `cd` into this directory and run `bundle exec jekyll serve`. This should do it for you:

```text
$ mkdir docs
$ cd docs
$ echo 'source "https://rubygems.org"' > Gemfile
$ echo 'gem "github-pages", group: :jekyll_plugins' >> Gemfile
$ bundle install
$ echo "# Test page" > index.md
$ bundle exec jekyll serve
```
