### ISSUE TITLE
Add me!

### ISSUE THREAD

**Issue by saraaaaahx** [github/pages-gem#504]
### Before submitting an issue, please be sure to

- [ ] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [ ] Update to the latest Gem version (run `bundle update github-pages`)

## Before suggesting a Jekyll plugin, please make sure the plugin is

- [ ] useful for a vast majority of users
- [ ] available as a gem
- [ ] covered with a test suite
- [ ] actively maintained

### This issue affects

- [ ] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#where-to-get-help-or-report-an-issue).*

### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

**Comment by parkr** [comment]
Closing as the issue template isn’t filled out. Please fill out the template and I’ll open again!
