### ISSUE TITLE
Update kramdown, please?

### ISSUE THREAD

**Issue by janpio** [github/pages-gem#505]
`kramdown` is currently pinned to 1.14.0:
https://github.com/github/pages-gem/blob/450f2e738dba992758fc08df345e18ad90fc08a1/lib/github-pages/dependencies.rb#L14

Up until 1.14.0 there was an issue if you include a link in a headline, the ToC generated by kramdown will not link to the headline but include the same link, thus breaking the ToC functionality of course:
https://github.com/gettalong/kramdown/issues/434

Version 1.15.0 included a fix for this issue:

> Fix TOC entries by removing nested links
https://kramdown.gettalong.org/news.html#kramdown-1150-released

Would you consider updating the dependency to 1.15.0 (or higher) to make this fix available on Github Pages?

**Comment by cetinajero** [comment]
This issue was fixed here:

https://github.com/github/pages-gem/blob/0ad4023694d2e4cb6b124c97139b890b4a0433a5/lib/github-pages/dependencies.rb#L14

Maybe you can close it 👍

**Comment by parkr** [comment]
Thanks for your patience on this one!

**Comment by janpio** [comment]
Thanks for updating, didn't really take long :)
