### ISSUE TITLE
Consider making available filters such as Haml

### ISSUE THREAD

**Issue by joallard** [github/pages-gem#513]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

## Before suggesting a Jekyll plugin, please make sure the plugin is

- [ ] useful for a vast majority of users
- [ ] available as a gem
- [ ] covered with a test suite
- [ ] actively maintained

(we'll see what gems we want and then we'll figure that out)

### This issue affects

- [x] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#where-to-get-help-or-report-an-issue).*

---

I've struggled with authoring Github pages sites using Haml for a while. The solution is pretty inelegant, as you pretty much run the converter on your source Haml and generate some Html that is going to be checked in. You'll then have two versions in your Jekyll source, the Haml and Html.

Now I know not the whole world uses Haml or other Html generators (such as Slim, etc.), but I'd appreciate having some kind of way to use it without resorting to a solution that inelegant.

Any interest in bundling a gem that would take care of that?

**Comment by benbalter** [comment]
> Any interest in bundling a gem that would take care of that?

General GitHub Pages feature requests, including requests to add additional plugins or themes should be made via [GitHub Support](https://github.com.contact).
