### ISSUE TITLE
Should update nokogiri > 1.8.1 because security vulnerability

### ISSUE THREAD

**Issue by mengkheang** [github/pages-gem#522]
I got security vulnerability alert because github page gem still using nokogiri 1.7.2 see [Github Page Version](https://pages.github.com/versions/)

<img width="967" alt="screen shot 2018-01-31 at 3 59 46 pm" src="https://user-images.githubusercontent.com/8617506/35613863-d11dcc14-069f-11e8-9d62-001c4406f08f.png">

**Comment by benbalter** [comment]
Please see https://github.com/github/pages-gem/pull/523.
