### ISSUE TITLE
Dependency error on jekyll-remote-theme around libcurl

### ISSUE THREAD

**Issue by SeanKilleen** [github/pages-gem#526]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- Building sites locally

### What did you do (e.g., steps to reproduce)

I'm assisting someone in getting their site converted from Blogger to GitHub. 

* Clone the repo (in this case, `dennisdoomen\dennisdoomen.github.io`)
* Check the gemfile (it only includes `gem "github-pages", group: :jekyll_plugins`)
* Run `bundle install`
* Run `bundle update github-pages`
* See no errors
* Run `bundle exec jekyll serve`

### What did you expect to happen?

* The site to be built & shown locally

### What happened instead?

I see an error: 

>   Dependency Error: Yikes! It looks like you don't have jekyll-remote-theme or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Could not open library 'libcurl': The specified module could not be found. . Could not open library 'libcurl.dll': The specified module could not be found. . Could not open library 'libcurl.so.4': The specified module could not be found. . Could not open library 'libcurl.so.4.dll': The specified module could not be found. ' If you run into trouble, you can find helpful resources at 
 https://jekyllrb.com/help/!

### Additional information

* Link to the live site (if applicable): http://dennisdoomen.github.io
* Link to the source repo (if applicable): http://github.com/dennisdoomen/dennisdoomen.github.io.
* Ruby version: `ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]`
* Bundler version: `Bundler version 1.15.1`
* OS: Windows 10

**Comment by SeanKilleen** [comment]
I thought this might have been an issue with PowerShell using `curl` as an alias for `Web-Invoke` so I:

* Removed the alias from my Powershell Profile
* Confirmed that `curl` no longer worked.
* Installed curl via chocolatey using `choco install curl`. 
* Restarted
* Attempted `bundle exec jekyll serve` again.

No luck.

**Comment by SeanKilleen** [comment]
A workaround for me was described [in this post](http://talk.jekyllrb.com/t/error-with-github-pages-locally/1239/6):

* Downloaded libcurl DLLs 
* Copied them into my ruby install's `bin` folder

This appears to get me past the hurdle, but it feels a biiiiiit hacky.

**Comment by parkr** [comment]
I know this is an old issue, but this should now no longer be a problem! jekyll-remote-theme migrated to use Ruby's built-in `Net::HTTP` library which does not use/require `libcurl`: https://github.com/benbalter/jekyll-remote-theme/pull/26
