### ISSUE TITLE
Problem with the SSL CA cert while testing the website locally.

### ISSUE THREAD

**Issue by sahilarora535** [github/pages-gem#529]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

1. Ran `bundle update`.
2. Ran `bundle exec jekyll serve`.

### What did you expect to happen?

I expected the site to build locally.

### What happened instead?

It showed an SSL error while building the file locally. On the `github` server, the site is rendered correctly, but I am unable to run it locally.

```
Configuration file: /home/sahil/ws/my-site/_config.yml
            Source: /home/sahil/ws/my-site
       Destination: /home/sahil/ws/my-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
jekyll 3.6.2 | Error:  Problem with the SSL CA cert (path? access rights?)
```
### Additional information

* Link to the live site (if applicable): <https://sahilarora535.github.io>
* Link to the source repo (if applicable): <https://github.com/sahilarora535/sahilarora535.github.io>

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular setup. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸
