### ISSUE TITLE
Missing tags for v176 and v177

### ISSUE THREAD

**Issue by kolyshkin** [github/pages-gem#537]
It [looks like](https://github.com/github/pages-gem/releases) that v176 and v177 tags haven't made it to this repo. I can clearly see v176 and v177 in commits but not in tags/releases. Perhaps you forgot to push tags to github?

**Comment by kolyshkin** [comment]
@benbalter PTAL

**Comment by kolyshkin** [comment]
@kivikakk PTAL

**Comment by parkr** [comment]
Just pushed https://github.com/github/pages-gem/releases/tag/v176 and https://github.com/github/pages-gem/releases/tag/v177.

**Comment by kolyshkin** [comment]
Thank you!
