### ISSUE TITLE
Issue installing gem - find compatible versions for gem "jekyll":

### ISSUE THREAD

**Issue by kirill-andr** [github/pages-gem#540]
When I do bundle install, I get the following error:
`The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

    jekyll-feed (~> 0.6) was resolved to 0.9.3, which depends on
      jekyll (~> 3.3)`

I am not a ruby expert and I have tried to:
specify version in Gemfile
bundle update

nothing seems to be working

**Comment by benbalter** [comment]
`github-pages was resolved to 4`

The latest version is [`177`](https://github.com/github/pages-gem/releases/tag/v177). You may need to explicitly specify the version e.g., `gem "github-pages", ">= 177"` in your Gemfile to get the latest version.
