### ISSUE TITLE
[Vulnerability] CGI Generic SQL Injection (blind) 443 / tcp / www

### ISSUE THREAD

**Issue by laukstein** [github/pages-gem#541]
I recently scanned GitHub Page using CloudFlare DNS with HackerGuardian PCI Scan, and it shows 2 
vulnerabilities.

> CGI Generic SQL Injection (blind) 443 / tcp / www

Second vulnerability open as #542

![grabilla uh4100](https://user-images.githubusercontent.com/183966/37426944-7fc35bd4-27d0-11e8-818a-1879fb1a59d8.png)

**Comment by benbalter** [comment]
@laukstein If you believe you've found a security vulnerability in GitHub Pages, please see GitHub's [responsible disclosure policy](https://help.github.com/articles/responsible-disclosure-of-security-vulnerabilities/).

**Comment by laukstein** [comment]
@benbalter I open it in https://hackerone.com/github as #325985 "Other applications" since doesn't allow to open for Github Pages.

**Comment by laukstein** [comment]
@benbalter by some reason Hackerone automatically closes the report for this vulnerability, see https://hackerone.com/reports/325985
