### ISSUE TITLE
github pages fails only on a specific organization

### ISSUE THREAD

**Issue by kvhnuke** [github/pages-gem#546]
### Before submitting an issue, please be sure to

- [X] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [X] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [X] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### Issue
Github pages fails on @myetherwallet org, this happens in all repos. If I fork the exact repo to a different organization or personal account it works fine. TravisCI passes as well

* Link to the source repo (if applicable):
https://github.com/MyEtherWallet/knowledge-base
https://github.com/MyEtherWallet/knowledge-base1
https://github.com/MyEtherWallet/test-gh

**Comment by benbalter** [comment]
This forum is intended to a bug tracker for the GitHub Pages gem, used to preview GitHub Pages sites locally. We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸
