### ISSUE TITLE
Dividing a variable returns 0 when 1 is expected

### ISSUE THREAD

**Issue by LordKanelsnegle** [github/pages-gem#574]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [ ] Building sites locally

### What did you do (e.g., steps to reproduce)
I wrote the following code:
```
{% assign postCount = site.posts | size %}
{% assign postMod = postCount | modulo:9 %}
{% assign postGap = 9 | minus:postMod %}
{% assign postCompensation = postCount | plus:postGap %}
{% assign pageCount = {{ postCompensation | divided_by:9 }} %}
<p>{{ postCount }}</p>
<p>{{ postMod }}</p>
<p>{{ postGap }}</p>
<p>{{ postCompensation }}</p>
<p>{{ pageCount }}</p>
```

### What did you expect to happen?
The website has 4 posts, so I expected to see something like this:
4
4
5
9
1

### What happened instead?
The following was outputted:
4
4
5
9
0

### Additional information
I have absolutely no idea why 9 divided by 9 is resolving as 0. I tried doing simply `{{ 9 | divided_by:9 }} ` and that outputted 1 as expected, so the issue didn't seem to be the dividing. I then checked if dividing a variable was the issue by doing 
```
{% assign x = 9 %}
{{ x | divided_by:9 }}
```
and that also outputted 1, leaving me even more stumped than I was before. I have absolutely no clue what the problem could be.

**Comment by honemepool** [comment]
Good

**Comment by honemepool** [comment]
What a

**Comment by benbalter** [comment]
@LordKanelsnegle this is likely a problem with the templating engine, Liquid, as is best addressed there: https://shopify.github.io/liquid/
