### ISSUE TITLE
v188 Jemoji does not work, breaks code blocks

### ISSUE THREAD

**Issue by bobheadxi** [github/pages-gem#578]
Seemingly related: https://github.com/jekyll/jemoji/issues/80

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

### What did you do (e.g., steps to reproduce)

```yml
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin
  - jekyll-mentions
  - jemoji
```

```md
\```bash
echo 'hello world' # without the escapes
\```
```

deploy to GH pages/`bundle exec jekyll serve`

### What did you expect to happen?

Emoji to render, code block to render correctly

### What happened instead?

No emoji (was previously working): https://bobheadxi.github.io
Example of code block breaking:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/23356519/42923776-2e3eb258-8adc-11e8-85f8-653c120021a7.png">

```html
<p>...has to be generated:</p> 
  <div class="language-text highlighter-rouge">
  <div class="highlight">
  <pre class="highlight">
  <code>Original:   AATGTCGATTCGA   -&gt;  Reverse Complement: TCGAATCGACATT
                 |    |
Converted:  AATGTTGATTTGA   -&gt;  Reverse Complement: TCAAATCAACATT

  <p>Note that the the original sequence’s reverse complement is not the bisulfite conversion of the original sequence’s bisulfite conversion’s reverse complement (yikes, that was a mouthful). This means that another sequence must be taken into account:</p> 
  <div class="language-text highlighter-rouge">
  <div class="highlight">
  <pre class="highlight">
  <code>Original RC:   TCGAATCGACATT
                |    |  |
  Converted RC:  TTGAATTGATATT
  </code></pre>
```

Not sure what's causing the first `<code>` tag to not close, but when I disable the `jemoji` plugin it works fine again.

### Additional information

* Link to the source repo (if applicable): https://github.com/bobheadxi/bobheadxi.github.io

I've disabled the jemoji plugin and the code blocks are fine now

**Comment by parkr** [comment]
An immediate fix could be to downgrade to v0.9.0.

**Comment by bobheadxi** [comment]
Thanks for looking into this @parkr!

**Comment by ashmaroli** [comment]
@bobheadxi A fix for this has been proposed at jekyll/jemoji#82. I've successfully tested your site's repo against the PR's branch..

**Comment by bobheadxi** [comment]
That's good to hear, thank you @ashmaroli

**Comment by bobheadxi** [comment]
This seems to have been resolved - thanks all!
