### ISSUE TITLE
Version mismatch in https://pages.github.com/versions.json

### ISSUE THREAD

**Issue by yatil** [github/pages-gem#588]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

I typed `bundle exec jekyll serve`.

### What did you expect to happen?

My site would run.

### What happened instead?

I get the following error message: `Could not find gem 'github-pages (= 191.1)' in any of the gem sources listed in your Gemfile.`

### Additional information

I use the following snippet in my Gemfile to always retrieve the latest version of the gem:

```
source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']
```

This worked fine over the last year or so, but now the https://pages.github.com/versions.json shows `191.1` as the current version, which cannot be found at the moment. (Latest version, as of writing this, that is available on rubygems is 191.)

**Comment by bajamircea** [comment]
I have the same problem. Might it be related to the outage on the 6th of September of rubygems?
http://uptime.rubygems.org/

**Comment by bajamircea** [comment]
Probably similar process to update as for issues #199, #166 etc.

**Comment by parkr** [comment]
Fixed by https://github.com/github/pages-gem/pull/590.

**Comment by yatil** [comment]
Thanks @parkr!
