### ISSUE TITLE
GitHub send me warning emails if I uses CommonMarkGhPages as markdown engine

### ISSUE THREAD

**Issue by EFanZh** [github/pages-gem#592]
I got the following email after updating my GitHub Pages markdown engine to CommonMarkGhPages.

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are currently using the 'commonmarkghpages' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

Is this the expected behavior?

**Comment by mattr-** [comment]
Per https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/ GitHub Pages only supports `kramdown`, so yes, this is expected behavior. Please remove the `markdown` setting from your site's `_config.yml` per the instructions you received in the email.

Thanks! :heart:

**Comment by EFanZh** [comment]
@mattr- But according to the code here:

https://github.com/github/pages-gem/blob/5bc41a93ded7b896012b8a517deb474e084f3428/lib/github-pages/configuration.rb#L142-L153

It seem that CommonMarkGhPages is supported.

**Comment by mattr-** [comment]
`commonmarkghpages` is only there for backwards compatibility and I wouldn't recommend using it going forward. `kramdown` is officially supported, along with `gfm` (which renders markdown using the same rules github.com uses to render markdown blobs on the site)

**Comment by EFanZh** [comment]
Yes, you are right. I don’t receive warning emails any more. As a matter of fact, I just want a CommonMark engine. The Kramdown syntax is inconsistent with my editor’s engine’s markdown syntax, which is CommonMark. Maybe GitHub should mention “gfm” this in its official document.

**Comment by cup** [comment]
https://github.com/github/jekyll-commonmark-ghpages/issues/9

**Comment by cup** [comment]
per the linked issue - it seems what @mattr- said is not correct

**Comment by mattr-** [comment]
Yup, my earlier comment is now outdated. I've updated it to reflect current reality.

**Comment by regakakobigman** [comment]
Has this changed? I'm receiving warnings for using CommonMarkGhPages.
