### ISSUE TITLE
<details><summary>... content fails to render

### ISSUE THREAD

**Issue by bittlingmayer** [github/pages-gem#593]
### This issue affects

- The site generated by GitHub Pages

### What did you do (e.g., steps to reproduce)

I used `<details><summary>...</summary></details>`.

See the full instructions at https://stackoverflow.com/questions/52944720/content-of-collapsible-sections-detailssummary-renders-markdown-in-gith.

### What did you expect to happen?

Render the markdown in the collapsible section, just like on GitHub.

It is much easier if Pages and READMEs are consistent on these nuances.

### What happened instead?

The markdown is rendered as a literal.

### Additional information

* Link to the live site (if applicable): https://deepchar.github.io/
* Link to the source repo (if applicable): https://github.com/deepchar/deepchar.github.io

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸

**Comment by bittlingmayer** [comment]
The site is a totally vanilla site and essentially minimal example, just to highlight the issue.  I'm happy to make another one.

The question is if this behaviour is unexpected and undesirable ie a bug or WAI.
