### ISSUE TITLE
Update Rouge to 3.x

### ISSUE THREAD

**Issue by TWiStErRob** [github/pages-gem#601]
Rouge version 3.x has been released for over a year now, is there any reason for not updating to it?

https://github.com/jneen/rouge/blob/master/CHANGELOG.md#version-300-20170921

**Comment by Krinkle** [comment]
There've also been a number of bugs fixed in 3.x that were previously causing error-colors to be used for valid syntax, such as "\n" in a string in JavaScript. Would recommend at least 3.2.0 or higher.

https://github.com/jneen/rouge/blob/v3.2.0/CHANGELOG.md

**Comment by cup** [comment]
https://github.com/github/pages-gem/issues/601
https://github.com/github/pages-gem/pull/597
https://github.com/github/pages-gem/pull/635
https://github.com/github/pages-gem/pull/642

**Comment by cup** [comment]
https://github.com/github/jekyll-commonmark-ghpages/pull/5

https://github.com/github/pages-gem/issues/601
https://github.com/github/pages-gem/pull/597
https://github.com/github/pages-gem/pull/635
https://github.com/github/pages-gem/pull/642
