### ISSUE TITLE
Update whitelist

### ISSUE THREAD

**Issue by cup** [github/pages-gem#604]
I see this list:

http://pages.github.com/versions

However comparing it against

https://github.com/github/pages-gem/blob/fb5c3f22a5789aee30c942e30962a69a8ac75e3a/lib/github-pages/plugins.rb#L22-L41

reveals that these are missing:

- jekyll-include-cache
- jekyll-octicons

**Comment by cup** [comment]
https://github.com/jekyll/jekyll/issues/7416

**Comment by parkr** [comment]
The gems that are reported via `site.github.versions` (which pages.github.com uses) is here:

https://github.com/github/pages-gem/blob/fb5c3f22a5789aee30c942e30962a69a8ac75e3a/lib/github-pages/dependencies.rb#L8-L49

You'll notice that those two gems are omitted here.
