### ISSUE TITLE
JavaScript files content-type should be text/javascript, not application/javascript

### ISSUE THREAD

**Issue by laukstein** [github/pages-gem#612]
Scan any GitHub Page having JavaScript assets (for example https://pages.github.com) with https://github.com/webhintio/hint, you will notice error

> https://webhint.io/scanner/43901e11-76c0-4074-99eb-ed897d3086a4#hint-content-type-2
> 'content-type' header media type value should be 'text/javascript', not 'application/javascript'

![grabilla em1328](https://user-images.githubusercontent.com/183966/50893645-03f30f00-140a-11e9-83bc-c7a2903fc73c.png)

**Comment by benbalter** [comment]
Please see https://help.github.com/articles/mime-types-on-github-pages/.

> To add or modify MIME types for use on GitHub Pages, see the [mime-db Contributing instructions](https://github.com/jshttp/mime-db#adding-custom-media-types).
