### ISSUE TITLE
https://pages.github.com/versions/ out of date?

### ISSUE THREAD

**Issue by mrmanc** [github/pages-gem#621]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

Compared version of `jekyll-github-metadata` on https://pages.github.com/versions/ and `bundle exec github-pages versions`

### What did you expect to happen?

I thought the versions would match.

### What happened instead?

`bundle exec github-pages versions` shows version 2.12.1
https://pages.github.com/versions/ shows version 2.9.4

### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

This sounds similar to #606 but I wanted to be explicit about versions. Apologies if I’ve misunderstood the process, but my understanding from reading the README and the published site is that the two should be in sync. I’m just trying to work out when https://github.com/jekyll/github-metadata/pull/147 is likely to be available in a GHE release.

**Comment by benbalter** [comment]
This should now be fixed after rebuilding the site. Thanks!
