### ISSUE TITLE
AsciiDoc

### ISSUE THREAD

**Issue by cup** [github/pages-gem#624]
AsciiDoc is currently supported on github.com, but not github.io. AsciiDoc is
appealing as it offers some missing feature from markdown, for example
Description List:

~~~
first term:: definition of first term
second term:: definition of second term
~~~

and admonitions:

~~~
:caution-caption: :fire:

CAUTION: hello world
~~~

while still offering graceful syntax highlighting:

~~~
[source,rb]
----
puts 'hello world'
----
~~~

and it offers autolinking which "jekyll-commonmark-ghpages" has but not
"kramdown".

- https://asciidoctor.org/docs/asciidoc-syntax-quick-reference#links
- https://asciidoctor.org/docs/asciidoc-syntax-quick-reference#lists
- https://asciidoctor.org/docs/asciidoc-syntax-quick-reference#source-code
- https://asciidoctor.org/docs/user-manual#unicode-admonition-icons
- https://github.com/github/markup#markups

resolution
----------

to fix, the gem "jekyll-asciidoc" would need to be added to the dependencies and
the whilelist.

https://github.com/github/pages-gem/blob/7fc4cadeffe708f3645a0428d480b43c65a87dd3/lib/github-pages/dependencies.rb#L13-L15
https://github.com/github/pages-gem/blob/7fc4cadeffe708f3645a0428d480b43c65a87dd3/lib/github-pages/plugins.rb#L20-L23

- https://github.com/asciidoctor/asciidoctor
- https://github.com/asciidoctor/jekyll-asciidoc

**Comment by cup** [comment]
https://github.com/asciidoctor/jekyll-asciidoc/issues/209
https://github.com/asciidoctor/jekyll-asciidoc/issues/26
https://github.com/github/pages-gem/issues/624

**Comment by benbalter** [comment]
@cup per [the CONTRIBUTING file](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#how-to-suggest-a-feature-or-enhancement), feature requests should be directed to GitHub Support. Thanks!

**Comment by cup** [comment]
@benbalter seeing how another request i sent 5 months ago is still broken - i dont think ill be doing that.

~~~
Date: Fri, 14 Sep 2018 09:47:32 -0500
Message-ID: <CAAXzdLUz28rPPEkb17zAg_mvZmAciOdFFOtgWSpUa4hJuw+9mg@mail.gmail.com>
Subject: repo language color missing
From: Steven Penny <svnpenn@gmail.com>
To: "Brian Levine (GitHub Staff)" <support@github.com>
Content-Type: text/plain; charset="UTF-8"

my "AWK" repos used to be colored gray

now they have no color

see here

https://github.com/cup
~~~
