### ISSUE TITLE
Whitelist jekyll-postfiles plugin

### ISSUE THREAD

**Issue by ration** [github/pages-gem#629]
Any chance to whitelist the [jekyll-postfiles](https://github.com/nhoizey/jekyll-postfiles) plugin? It makes writing blog posts a lot easier as any markdown editor with a preview function works properly as the image paths are correct.

**Comment by benbalter** [comment]
Please see https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#how-to-suggest-a-feature-or-enhancement.
