### ISSUE TITLE
Bump liquid from 4.0.0 to 4.0.1+ to fix sort_natural NPE

### ISSUE THREAD

**Issue by soundasleep** [github/pages-gem#638]
### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

### Additional information

In liquid 4.0.0, there is a bug with `sort_natural` where it can crash when trying to sort arrays with `nil`. This occurs when trying to sort `site.posts` or `site.pages` on `title` when using `jekyll-redirect-from`: https://github.com/jekyll/jekyll-redirect-from/issues/200

I believe this has been fixed in liquid 4.0.1+. https://github.com/Shopify/liquid/commit/deb10ebc7a8b1979b7c5daec83f2e69d9b68591d

This gem is still locked to 4.0.0. Is there any plan to upgrade liquid?

**Comment by parkr** [comment]
Hi! We could certainly look into this. I've begun the automated process here: https://github.com/github/pages-gem/pull/639

**Comment by shreve** [comment]
What's the process to move this forward? A lot of the other dependency version bumps I've seen in this repo were merged within a couple days.
