### ISSUE TITLE
Jekyll Archives work only in localhost.

### ISSUE THREAD

**Issue by alonshrestha** [github/pages-gem#650]
Hello, Can someone help me? I am using ['Affilated'](https://www.wowthemes.net/free-jekyll-template-affiliates/) themes. While testing the theme the "archive" function works fine on localhost but not in Github host.  It says "404 file not found".

**Comment by UlyssesZh** [comment]
I have the same issue!
In fact, as can be seen, jekyll-archives gem is not included [here](https://pages.github.com/versions/). We can only wait until it is included.
However, there is a workaround. Just run `jekyll build` and copy the whole "archives" directory to the root of your jekyll project. You can write a script yourself to implement this:
```sh
jekyll build
cp -r _site/archives .
git add archives
```

**Comment by kannansuresh** [comment]
Check this out [Automated Jekyll Archives for GitHub Pages](https://aneejian.com/automated-jekyll-archives-github-pages/).

**Comment by alonshrestha** [comment]
Thank you. This issue has persisted for some time, and I am no longer utilizing that theme. I am closing this issue.
