### ISSUE TITLE
Relax Active Support dependency

### ISSUE THREAD

**Issue by radar** [github/pages-gem#654]
This line locks ActiveSupport to 4.2.1.1:

https://github.com/github/pages-gem/blob/2747fa68f5248cb40be9fd272a039c2fad0e2ac7/lib/github-pages/dependencies.rb#L48

This 4.2.x branch of Rails started in 2014, and so this dependency is locked to a 5 year old branch.

Could we please have this dependency relaxed so that we can use any modern-ish version of ActiveSupport?

**Comment by parkr** [comment]
@radar Great point! Perhaps we should simply remove the explicit version locking in this repo.

**Comment by parkr** [comment]
Removed this in #664
