### ISSUE TITLE
Overlap of two elements

### ISSUE THREAD

**Issue by biesiadamich** [github/pages-gem#692]
### Before submitting an issue, please be sure to

- [ x ] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [ ] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ x] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)
Fill the repo description. Forked, pinned.

### What did you expect to happen?
Space between elements as usual.

### What happened instead?
Overlap two elements, as seen on attached screenshot (description of the repo section).

### Additional information
Browser: Firefox 77.0.1
The same with Chrome.

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

Screenshot:
![issue](https://user-images.githubusercontent.com/60202305/84504375-20107500-acbc-11ea-9472-aea76b41498c.png)

Best wishes,

**Comment by biesiadamich** [comment]
![issue_2](https://user-images.githubusercontent.com/60202305/84505670-6a92f100-acbe-11ea-9458-782bc02e70e0.png)

I see the same problem with other parts now (see above).

**Comment by DennisPan** [comment]
@biesiadamich Not sure I understand the issue. Are these UI from GitHub or the site your built?

**Comment by biesiadamich** [comment]
@DennisPan good question. That wasn't. I mean the UI of the GitHub for few days. Now looks OK. I know that I should create issue perhaps in other place, but I didn't find good place, so I decided here as 'more connected'. Now UI looks OK, I mean that is no overlap more, hm. I decided closed.
