### ISSUE TITLE
Misleading information about commonmark usage on github pages

### ISSUE THREAD

**Issue by ktzanev** [github/pages-gem#694]
I don't know if here is the right place to raise an issue about jekyll on github pages. 
If it is not, I'm sorry.

When I set in `markdown: CommonMark` in `_config.yml` I receive an email with the following information:

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are currently using the 'commonmark' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/en/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=273886489&page_build_id=187367904
> 

But when I go the [indicated pages](https://help.github.com/en/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll) there is no mention of no longer supported 'commonmark'. On this page we can read 

> GitHub Pages supports two Markdown processors: kramdown and GitHub's own extended CommonMark processer, which is used to render GitHub Flavored Markdown throughout GitHub.

Obviously the link provided in the email is not up to date.

**Comment by DennisPan** [comment]
@ktzanev In the doc, it explains two options for `markdown`:
![image](https://user-images.githubusercontent.com/14064342/85326043-6cf50800-b481-11ea-9e65-02e3f7335341.png)

That's why you are receiving the error. Note that the `commonMark` processor supported in GitHub Pages is its own extended version.

**Comment by ktzanev** [comment]
Sorry but I don't get it, because with `GFM` the error is the same. Only `kramdown` is allowed no ?

The mail says:
> remove the 'markdown' setting

And not choose between `kramdown` and `GFM` .

**Comment by DennisPan** [comment]
What's the new error message?

I just tried on a test repository with either `kramdown` or `GFM`. Both builds went fine (Check git history of https://github.com/DennisPan/testrepo/blob/master/_config.yml)

**Comment by ktzanev** [comment]
Sorry, I don't know what I messed up, but now with `markdown: GMF` it works perfectly without error message.
Thanks one more time for considering my question.
I close this issue.
