### ISSUE TITLE
Update rouge to 3.21.0

### ISSUE THREAD

**Issue by punchcutter** [github/pages-gem#697]
Not sure how hubot works with updating rouge, but we've been waiting and hoping it would get updated here soon to 3.20.0. Now 3.21.0 is out so that would also be good.    

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

**Comment by Mause** [comment]
Rouge is now at 3.26.0: https://github.com/github/pages-gem/blob/master/lib/github-pages/dependencies.rb#L20
