### ISSUE TITLE
Updating to 207 broke math on my site

### ISSUE THREAD

**Issue by ajakaja** [github/pages-gem#705]
### Before submitting an issue, please be sure to

- [*] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [*] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [*] The site generated by GitHub Pages
- [] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

Ran `bundle update`.
Math output is now rendered in `\[ \]` tags. Before updating, it was rendered in something like `<script type='math/tex; mode=display'>`. I'm probably using some old logic to parse these tags with KaTeX and it began failing today.

Not saying this is wrong -- those old tags look really janky and unnecessary. But it was a surprise, as there was nothing about changing math support mentioned in https://github.com/github/pages-gem/pull/704 (although there is a unit test asserting the new behavior). A FAQ entry on how to update this somewhere might be helpful. I am going to try to switch to using https://katex.org/docs/autorender.html. 

### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

**Comment by parkr** [comment]
@ajakaja We're very sorry about this! It was my understanding that MathJax JavaScript supported both.

Where do you think an FAQ entry would go?

I added a comment here: https://github.com/github/pages-gem/pull/704#issuecomment-670956711

**Comment by ajakaja** [comment]
I think it does, but I'm using KateX which works differently and I installed it a long time ago so was running it by hand -- taking the output and just invoking `katex.renderToString` directly on it. It was working but it wasn't necessarily maintainable.

Ideally there would be mentioned somewhere around https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll -- that's the documentation I went to for debugging.

I'm having trouble finding the documentation for the kramdown `math_engine_opts` configurations -- it _seems_ like it should be possible to configure kramdown to emi whatever I want. Haven't figured it out yet.

**Comment by ajakaja** [comment]
Okay, Katex's autorender plugin worked fine: https://github.com/ajakaja/ajakaja.github.io/commit/37663a07af8650b6b09bc0347126c9187ab5f13f

I replaced my customized script with something like this:
```
document.addEventListener("DOMContentLoaded", function() {
  renderMathInElement(document.body, {});
});
```
and got back where I was with little difficulty.
