### ISSUE TITLE
using mathjax and $$ equation $$ syntax

### ISSUE THREAD

**Issue by AlexandreGilotte** [github/pages-gem#708]
Hi,
I am trying to use mathjax  to display latex on github pages.
However, equations written with the syntax   $$ formula $$  are not displayed properly on the github pages website.

The issue may be seen on this page:  https://alexandregilotte.github.io/CounterfactualEstimator/test.html

Note that:
-  Equations using the inline syntax with a single "$",  like  $ formula $ , are correctly displayed (so mathjax does something)
- When I run the website locally, both types of formulas are correctly displayed.

I also checked the source code of the returned webpages:
- on githubpages, $$ formula $$ was replaced by  \\[ formula \\]
- on my local jekyll server it is instead replaced by a html tag <script type="math/tex; mode=display"> formula  </script>

I then tried replacing myself the '$$' in the markdown by those html tags, and when doing so theequations are correctly displayed. It feels however quite hacky to do so, how can I fix it more cleanly  ?

* Link to the live site https://alexandregilotte.github.io/CounterfactualEstimator/test.html

### Additional information
- I am using kramdown
- I imported mathjax in the default layout, from 
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
I saw somewhere that cdn.mathjax.org was at some point obsolete, but it seems live again now ?

**Comment by parkr** [comment]
Hi @AlexandreGilotte!

Due to a recent kramdown CVE, we upgraded to the latest version of kramdown, v2.3.0. Make sure you're up-to-date locally, running Jekyll 3.9.0 and kramdown 2.3.0.

In kramdown 2.3.0, they shifted from outputting `<script>` tags to now outputting `\[ ... \]` for block math.

In your site, you have some JavaScript configuration:

```js
MathJax.Hub.Config({
    TeX: {
      equationNumbers: {
        autoNumber: "AMS"
      }
    },
    tex2jax: {
    inlineMath: [ ['$', '$'] ],
    displayMath: [ ['$$', '$$'] ],
    processEscapes: true,
  }
});
```

I'd recommend changing `displayMath`'s values to use the new `\[` and `\]` values.

```js
MathJax.Hub.Config({
    TeX: {
      equationNumbers: {
        autoNumber: "AMS"
      }
    },
    tex2jax: {
    inlineMath: [ ['$', '$'] ],
    displayMath: [ ['\[', '\]'] ],
    processEscapes: true,
  }
});
```

Would you give that a try and see how things go?

**Comment by AlexandreGilotte** [comment]
Hi, yes it worked fine.
- The discrepancy between githubpages and local was indeed fixed once I updated kramdown
- The equations were then fixed by modifying the mathjax config as you suggested, but with an additional "\", ie    displayMath: [ ['\\[', '\\]'] ],   instead of  displayMath: [ ['\[', '\]'] ],    

Thanks a lot for the help !
