### ISSUE TITLE
Octicons are inconsistent

### ISSUE THREAD

**Issue by cloewen8** [github/pages-gem#709]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)
Used jekyll-octicons in a navigation menu.

### What did you expect to happen?
GitHub's current icons from the Octicons plugin (as observed locally).

![image](https://user-images.githubusercontent.com/1569808/94217083-5d30f980-fe9e-11ea-95e9-bc7cd6c65213.png)

### What happened instead?
An older or different version of the icons.

![image](https://user-images.githubusercontent.com/1569808/94217133-79349b00-fe9e-11ea-9dbf-e16245bb0a3f.png)

It is especially apparent in the house icon doorway.

### Additional information

* Link to the live site (if applicable): cjloewen.ca
Can be seen on the left under Contents (large screens) or the bottom navigation (smaller screens).

Gemfile:
```ruby
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

gem 'jekyll-octicons'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?
```

**Comment by cloewen8** [comment]
It has been a few months now. Any updates on this?

**Comment by parkr** [comment]
Perhaps check your version of jekyll-octicons against https://pages.github.com/versions/ ? That page will tell you if there's a different version. If so, then it's possible to have different SVG's for new designs.

**Comment by cloewen8** [comment]
> 
> 
> Perhaps check your version of jekyll-octicons against https://pages.github.com/versions/ ? That page will tell you if there's a different version. If so, then it's possible to have different SVG's for new designs.

Octicons is not listed there. I suspect since it is not included by default (only whitelisted). The version I have installed locally is *11.2.0*.
I can't verify if it is a version difference or not. But I doubt it's anything else. Why would Octicons have different designs in the same version?

**Comment by cloewen8** [comment]
It appears this has been resolved!

Not sure which commit resolved this. Would love to know if anyone spots it. Regardless, thank you!
