### ISSUE TITLE
Please update to Kramdown 2.3.1

### ISSUE THREAD

**Issue by aaguilera** [github/pages-gem#767]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

Got alert from Dependabot addressing a [_high severity issue_ in Kramdown](https://github.com/advisories/GHSA-52p9-v744-mwjj). The issue seems to affect GitHub Pages Ruby Gem 213, which depends on kramdown 2.3.0.

### Additional information

* Link to the live site (if applicable):
* Link to the source repo (if applicable):

**Comment by aaguilera** [comment]
Sorry, I just checked this has been resolved already for the next version.

**Comment by armoured-moose** [comment]
see #762

**Comment by aaguilera** [comment]
I see. Sorry!

**Comment by Derar1986** [comment]
😳
