### ISSUE TITLE
Three.js animations and styling not appearing on live site.

### ISSUE THREAD

**Issue by GarrettBrown-dev** [github/pages-gem#773]
Hello all! I'm having some issues with the deployment of my new portfolio which incorporates some Three.js animations for some extra pop. (I created the project with Vite.) The issue I'm having is all the styling and animations aren't showing up. the console says it's a 404 error, but everything works perfectly locally. I tried adding a .nojekyll file, I even tried adding the node_modules folder in a separate branch, but no luck. At one point the console said "cannot load three, must start with ./, / etc. but if I change the routes locally, it causes errors... I'm not totally sure what to do now, as I've been trying to solve this for about 3 hours. I just want my new sexy site up. D:

Live Site: https://garrettbrown-dev.github.io/MyPortfolio/
Repo: https://github.com/GarrettBrown-dev/MyPortfolio

**Comment by Dholc2021** [comment]
I am having the same issue. It works fine on the live server but the texture does not show up in github pages.

**Comment by Pranshu-Sahu** [comment]
I also have similar problem. 
Live site https://effulgent-dango-c0a969.netlify.app/

**Comment by yoannchaudet** [comment]
I think https://github.com/orgs/community/discussions/categories/pages would be a better place for this kind of support!
