### ISSUE TITLE
Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss'

### ISSUE THREAD

**Issue by remarkablemark** [github/pages-gem#776]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

Bump `github-pages` from 215 to 216.

### What did you expect to happen?

Build completes with no errors.

### What happened instead?

Build throws errors:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
jekyll 3.9.0 | Error:  File to import not found or unreadable: architect.
                    File to import not found or unreadable: architect. Load paths: /home/runner/work/remarkablegames.github.io/remarkablegames.github.io/_sass /home/runner/work/remarkablegames.github.io/remarkablegames.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-architect-0.1.1/_sass /tmp/jekyll-remote-theme-20210723-1610-1jifx4r/_sass on line 1
Load paths:
/home/runner/work/remarkablegames.github.io/remarkablegames.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: architect. (Jekyll::Converters::Scss::SyntaxError)
  /home/runner/work/remarkablegames.github.io/remarkablegames.github.io/_sass
Load paths:
  /home/runner/work/remarkablegames.github.io/remarkablegames.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-architect-0.1.1/_sass
  /home/runner/work/remarkablegames.github.io/remarkablegames.github.io/_sass
  /tmp/jekyll-remote-theme-20210723-1610-1jifx4r/_sass on line 1
  /home/runner/work/remarkablegames.github.io/remarkablegames.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-architect-0.1.1/_sass
```

See full [error stacktrace](https://github.com/remarkablegames/remarkablegames.github.io/pull/12/checks?check_run_id=3148027402#step:4:14).

### Additional information

* Link to the live site (if applicable): N/A
* Link to the source repo (if applicable): See https://github.com/remarkablegames/remarkablegames.github.io/pull/12

**Comment by parkr** [comment]
Hi! This should now be fixed with v217.
