### ISSUE TITLE
Versions out of sync

### ISSUE THREAD

**Issue by TWiStErRob** [github/pages-gem#810]
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

> The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally.

### What did you do (e.g., steps to reproduce)
Want to update my `Gemfile` to match GitHub's version.

### What did you expect to happen?
Find the specific version GitHub uses at the moment.

### What happened instead?
Confusion:
 * https://rubygems.org/gems/github-pages lists 219..223 (and older behind link)
 * https://github.com/github/pages-gem#github-pages-ruby-gem has a badge for 223
 * https://github.com/github/pages-gem/releases shows 221
 * https://pages.github.com/versions/ shows 219

At this point I can't tell if the `/versions/` page is outdated (August?!) or GitHub is not using the latest from its own project?!

Please clarify and update scripts/documentation to keep these 4 numbers in sync.

**Comment by TWiStErRob** [comment]
Note: not having 222 and 223 on GitHub releases also means it's hard to see what's changed.

**Comment by parkr** [comment]
@yoannchaudet Hey! Is there a way to run a Page Build job on the pages.github.com site periodically? Maybe a GitHub Action could fire off the build? Many folks use https://pages.github.com/versions/ (and `/versions.json`) to understand what gems they should use to match GitHub Pages, so ideally the site is rebuilt whenever you launch a new version to Pages. Thank you!

**Comment by yoannchaudet** [comment]
Hello here!

Thank you for pointing these inconsistencies, this was not intended.

Versions 222 and 223 did not include any changes relevant to the build process itself and just helped support https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/.

We should not be out of sync in so many locations! I'll make sure we update our procedure to release `pages-gem` so it does not happen again and so we clean stuff up in the next few days.

@parkr (hi!) yes! We can definitely automate the rebuilds for pages.github.com ❤️

**Comment by parkr** [comment]
@yoannchaudet Hi! Thank you so much! ❤️

**Comment by TWiStErRob** [comment]
Thanks @parkr for pointing to the right person!

And also for still being active around here after your departure to greener pastures. 🙇‍♂️💪

**Comment by yoannchaudet** [comment]
Forgot to close that with the last update. We should be in-sync everywhere or within a few hours during any upgrade.

**Comment by TWiStErRob** [comment]
Confirmed. Release 227 just went out 5 hours ago and it's everywhere except https://pages.github.com/versions/ which is on 226. Deployment might take a while as you said.
