### ISSUE TITLE
Bump Jekyll to v3.9.2

### ISSUE THREAD

**Issue by ashmaroli** [github/pages-gem#828]
- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

### Additional information

Jekyll v3.9.2 was released recently.
Looks like Hubot only tracks mainstream releases of Jekyll.

[Jekyll v3.9.0 ... Jekyll v3.9.2](https://github.com/jekyll/jekyll/compare/v3.9.0...v3.9.2)

**Comment by ashmaroli** [comment]
Attn: @yoannchaudet

**Comment by yoannchaudet** [comment]
Thank you! We will get this updated shortly.

**Comment by yoannchaudet** [comment]
Jekyll 3.9.2 is now available both with the legacy building infrastructure and https://github.com/actions/jekyll-build-pages/pkgs/container/jekyll-build-pages

**Comment by ashmaroli** [comment]
Thank you @yoannchaudet
