### ISSUE TITLE
Jekyll serve fails on Ruby 3.1.2 (webrick missing) 

### ISSUE THREAD

**Issue by pooraniarvind** [github/pages-gem#834]
Hi All,

I am new to Jekyll.

I get the following error when i run jekyll serve while building site locally:
Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)

Also why the script is asking to enable incremental build with --incremental.

TIA,
Poorani

**Comment by nickmccurdy** [comment]
Duplicate of #752

**Comment by pooraniarvind** [comment]
thanks Nick.
