### ISSUE TITLE
Liquid version on M1 Mac

### ISSUE THREAD

**Issue by stuartbman** [github/pages-gem#870]
### This issue affects
 Building sites locally

### What did you do (e.g., steps to reproduce)
Trying to follow instructions to install github-pages locally. Using ruby 3.2, macOS Monterey

On running `bundle exec jekyll serve` I get the following error
```
 Liquid Exception: undefined method 'untaint' for "Welcome to Jekyll!":String in /_layouts/post.html`
```
Looking at Jekyll issue tracker, this is an issue with Liquid, fixed in v 4.0.4: https://github.com/jekyll/jekyll/issues/9233 
When I add this to the gemfile (`gem "liquid", "~> 4.0.4"`), I get a version conflict:

```
Could not find compatible versions

Because github-pages >= 203, < 228 depends on liquid = 4.0.3
  and Gemfile depends on liquid ~> 4.0.4,
  github-pages >= 203, < 228 is forbidden.
So, because Gemfile depends on github-pages ~> 227,
  version solving has failed.
```

And when I try requiring `github-pages ~> 228`, it seems to be incompatible with M1 silicon due to a dependency:
```
Could not find gem 'http_parser.rb (= 0.8.0)' with platform 'x86_64-darwin-21' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'http_parser.rb (= 0.8.0)':
  * http_parser.rb-0.8.0
```

**Comment by parkr** [comment]
This is because you're using Ruby 3.2. A fix is in the works: https://github.com/github/pages-gem/pull/860

**Comment by parkr** [comment]
Upgrade to github-pages gem to v228. (https://github.com/github/pages-gem/pull/867)

**Comment by stuartbman** [comment]
Thanks this fixes it!
