### ISSUE TITLE
No syntax highlighting for Dafny

### ISSUE THREAD

**Issue by fabiomadge** [github/pages-gem#874]
### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

``` markdown
~~~ dafny
datatype D = A | B
~~~
```

### What did you expect to happen?

I want syntax highlighting for my favourite language.

### What happened instead?

No colours

### Additional information

I suspect that #871 would fix this.

**Comment by yoannchaudet** [comment]
Want to check if that works now that Rouge was updated?

**Comment by fabiomadge** [comment]
Thanks for the effort, but I gave up on waiting a few weeks ago and built a Workflow to gain some autonomy.
