### ISSUE TITLE
GitHub Pages Deployment Failing

### ISSUE THREAD

**Issue by matcdac** [github/pages-gem#885]
### Before submitting an issue, please be sure to

- [ ] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/docs/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [ ] Update to the latest Gem version (run `bundle update github-pages`)

### This issue affects

- [ Google-Ad-Sense.github.io ] The site generated by GitHub Pages
- [ ] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/docs/SUPPORT.md).*

### What did you do (e.g., steps to reproduce)

WebIDE commit push to trigger Actual deployment

### What did you expect to happen?

Deployment on GitHub.io

### What happened instead?

Deployment Failed

Refer
https://github.com/Google-Ad-Sense/Google-Ad-Sense.github.io/actions/runs/5444481740/jobs/9902404801

### Additional information

* Link to the live site (if applicable): https://google-ad-sense.github.io/
* Link to the source repo (if applicable): https://github.com/Google-Ad-Sense/Google-Ad-Sense.github.io/tree/main

**Comment by matcdac** [comment]
![image](https://github.com/github/pages-gem/assets/20089585/1d9743e0-4203-4938-b86e-9212c60e5e7d)

**Comment by parkr** [comment]
This repository is not for individual repo support. Please reach out to GitHub Support for help.

**Comment by yoannchaudet** [comment]
What @parkr is saying above ^

@matcdac If that was not a transient issue, don't hesitate to post in https://github.com/orgs/community/discussions/categories/pages or reach out to the [support directly](https://support.github.com/contact).

Deployments issues have nothing to do with this repository.
