### ISSUE TITLE
Consider adding `webrick` to the whitelist of allowed GitHub Pages dependencies to avoid build warnings

### ISSUE THREAD

**Issue by daattali** [github/pages-gem#887]
There are a few issues regarding updating the documentation around `webrick` not being available in Ruby 3, but this issue is about a different problem.

If I want to support local builds, I must manually add `webrick` to the Gemfile. However, because of a recent [change in jekyll-build-pages](https://github.com/actions/jekyll-build-pages/pull/61/files), this now results in a warning "github-pages can't satisfy your Gemfile's dependencies" for every build. This means that anyone who wants to host a GitHub Pages repo that uses the default jekyll builder, and also wants to be able to run locally, will always have to see a warning on every GitHub Actions build.

I don't know the security implications of allowing `webrick` in GitHub Pages, but I hope it can be done. If not, perhaps we should be able to remove that warning message somehow.

**Comment by ohadschn** [comment]
I believe there is a simple workaround, in your `Gemfile`:
```ruby
install_if -> { ENV["JEKYLL_ENV"] != "production" } do
    puts "non-prod environment detected - installing webrick HTTP server for local debugging"
    gem "webrick", "~> 1.8"
end 
```

`JEKYLL_ENV` seemed like the best condition to use, but you can find other options here: 
https://github.com/actions/jekyll-build-pages/blob/main/entrypoint.sh

**Comment by janbrasna** [comment]
No workaround should be needed since [v232](https://github.com/github/pages-gem/releases/tag/v232).

**Comment by parkr** [comment]
@yoannchaudet This issue can be marked completed.

**Comment by yoannchaudet** [comment]
Fixed via https://github.com/github/pages-gem/pull/914 then later https://github.com/github/pages-gem/pull/919!
