### ISSUE TITLE
Jekyll Archives on GitHub Pages

### ISSUE THREAD

**Issue by alfredxing** [github/pages-gem#93]
Hello GitHubbers (and everyone watching this repo)!

I (along with the Jekyll team & contributors) recently released the [Archives plugin](https://github.com/jekyll/jekyll-archives). The plugin generates archive pages based on tags, categories, and dates, similar to the behaviour of WordPress and other CMS's.

Do you think this gem would be useful enough for inclusion in GitHub Pages?

_This issue was originally posted as jekyll/jekyll#2958. The original issue requesting such a feature is at jekyll/jekyll#870._

**Comment by dblock** [comment]
+1

**Comment by marceloboeira** [comment]
+1

**Comment by benbalter** [comment]
Thanks for the pull request @alfredxing (and for a great plugin). Closing in favor of #106 where I explained [why the feature doesn't fit into the roadmap at this time](https://github.com/github/pages-gem/pull/106#issuecomment-69336195).

**Comment by johnsyweb** [comment]
:+1:

**Comment by grudelsud** [comment]
sorry to reiterate, but providing a way to display lists of posts falling under same categories / tags / periods seems pretty basic functionality to me. would love to see this plugin working on github.

here a few findings while trying to circumvent this limitation:

- create and manage collections manually, by using [jekyll's collections feature](http://jekyllrb.com/docs/collections/) (still unstable) and implementing a bit of logic to show posts accordingly
- compile the site locally using the archive plugin and commit all the files manually in a "no jekyll" environment, as described [here](http://www.sitepoint.com/jekyll-plugins-github/)

of course the ideal would be to have the archive plugin being accepted as part of the jekyll core plugins and have it whitelisted to run on github

**Comment by MrLoh** [comment]
If anyone is looking for a GitHub Pages compatible completley automated date and tag archive solution, have a look at the solution I found: http://mrloh.se/2015/06/automatic-archives-for-jekyll-on-github-pages/

**Comment by zongren** [comment]
＋1
